### ISSUE TITLE
Consider making imagej-legacy optional

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej#108]
The use of the [LegacyService](https://github.com/imagej/imagej/blob/4ba509d0cfdc1fe998960ee397097ec985c6b31a/src/main/java/net/imagej/ImageJ.java#L168-170) creates a hard dependency on [ImageJ-Legacy](github.com/imagej/imagej-legacy). We may not want to force a dependency on ImageJ 1.x.

As an alternative, we could remove this method from the gateway, and make the imagej-legacy dependency scope:runtime and optional:true. Then consuming code can decide independently if it wants to pull in imagej-legacy.

**Comment by ctrueden** [comment]
Addressed by e8fbfeee858960f4a46aed8e0eb03175385d62fa!
