### ISSUE TITLE
Consider creating ImageJ forums

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej#112]
Some people (I'm looking at you, @dietzc!) really, really prefer forums. And others (like me) really hate them. But to be fair: subscribing to a mailing list just to ask one question is super annoying. So annoying that lots of people never do it. Forums are much more convenient. And easy to use. And rich—email is still so 1980s.

The thing I am _really_ against doing is having a separate forum and mailing list. I want _one_ place where people ask questions and give answers, Google Groups style. But @dietzc said that Google Groups's interface is not good enough. Plus we would lose control of the content (hosted externally) and be always at risk of the service shutting down. We need a self-hosted solution.

I have searched around several times for such a thing, and so far the best I can find is [tiki wiki's Forum and List synchronization](http://doc.tiki.org/Forum+and+Mailing+List+Synchronization) guide, which can hook up your forum to mailman (the software we currently use for imagej-devel). I have used Tiki in the past (~2005-2006) and it was pretty awesome, but not the prettiest. Maybe it would be worth a shot?

**Comment by ctrueden** [comment]
We should use [Discourse](http://discourse.org/). Definitely. DEFINITELY.

**Comment by tinevez** [comment]
A StackOverflow group?

**Comment by ctrueden** [comment]
@tinevez There is an imagej tag on StackOverflow, yeah, and some of us (me, @hinerm and @imagejan in particular) do follow it. But SO is not a discussion forum—it is actually the opposite: open-ended discussion is discouraged.

So Jeff Atwood, one of the founders of SO, invented this new tool called Discourse which is sort of "SO as a discussion forum." Excellent 21st century version of a forum which has been redesigned from the ground up. We can set it up on our servers and all our problems will be solved forever.

**Comment by tinevez** [comment]
Ok Looks very good indeed!

**Comment by ctrueden** [comment]
We did it. WE DID IT. http://forum.imagej.net/

And it is awesome.
