### ISSUE TITLE
Jython scripts can't be run headlessly on Windows

### ISSUE THREAD

**Issue by hinerm** [imagej/imagej#114]
Attempting to do so gives

```
java.lang.UnsatisfiedLinkError:
C:\Users\jrminter\AppData\Local\Temp\org.scijava.jython.shaded.jline_2_5_3.dll:
The process cannot access the file because it is being used by another process
```

See also [this imagej mailing list thread](http://imagej.1557.x6.nabble.com/Error-in-headless-mode-on-Windows-7-with-current-FIJI-ImageJ-installation-td5010280.html#a5011873).

May be solved by updating the jython version in [jython-shaded](https://github.com/scijava/jython-shaded)

**Comment by ctrueden** [comment]
Once this issue is resolved, the [corresponding warning on the wiki](http://imagej.net/Headless#Running_scripts_in_headless_mode) should be removed.

**Comment by tinevez** [comment]
I confirm the bug and symptoms on the win64 platform, running windows 8.1 or windows 7. 
The dll mention in @hinerm description in my case points to a dll that lives in the %AppData% folder.

**Comment by ctrueden** [comment]
With Jython 2.7.0, this problem seems to be gone, at least in my tests. Please reopen if you still experience the issue.
