### ISSUE TITLE
Allow passing parameters to scripts

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej#121]
Right now, there is no way to pass script parameter values via the command line; e.g.:
```
ImageJ-linux64 --headless fiji-plugins/HelloWorld.clj lena.jpg
```
ImageJ should definitely support this. The question is: how best to assign the parameter values to the inputs? We could use key/value pairs, or simply take the arguments in order of `@Parameter` declaration. This would be a great feature of ImageJ2 facilitated by the parameterized scripting framework, since AFAIK you cannot do this with ImageJ1's macro syntax, either.

See also [this thread on the ImageJ mailing list](http://imagej.1557.x6.nabble.com/Scripts-in-FIJI-with-command-line-arguments-tp5011265.html).

**Comment by abalter** [comment]
Very important because ImageJ is an extremely widely used collection of libraries that people use together, and more and more work is being done in an automated fashion on clusters. The need for this is only going to go up. I need it right now!

**Comment by dietzc** [comment]
Hi @abalter,

to automate stuff you can try to use http://knime.imagej.net.

Cheers,
Christian

**Comment by hinerm** [comment]
@abalter @dietzc @ctrueden this actually will be solved in once we release https://github.com/scijava/scijava-common/commit/5715522284a0e8c1e9951ecbb186ce4cfc802e91

**Comment by ctrueden** [comment]
Thanks @hinerm! We still need to document this new functionality. Maybe [on the Headless page](http://imagej.net/Headless#Running_scripts_in_headless_mode)?

@abalter Feel free to give it a spin (by updating to the latest Java 8 version of Fiji)—and if it works for you, you are welcome to document how to pass the parameters by editing the wiki. :smile: 

In brief: the syntax is key/value pairs separated by commas. The whole thing needs to be a single CLI argument—so either use no spaces, or quote it. E.g.:
```
ImageJ-linux64 --ij2 --headless --run fiji-plugins/HelloWorld.clj image=lena.jpg,tolerance=5
```
Alternately, you can also leave off the keys and the values are assumed to match the parameter order in your script—e.g.:
```
ImageJ-linux64 --ij2 --headless --run fiji-plugins/HelloWorld.clj lena.jpg,5
```
Lastly, please keep in mind that this feature is brand new, and may have various gotchas and limitations. Your feedback will be very helpful to refine it!

**Comment by hinerm** [comment]
>Thanks @hinerm! We still need to document this new functionality.

Moved [here](http://imagej.net/Scripting_Headless) to be easier to find in the scripting topics.

**Comment by ehrenfeu** [comment]
Actually, for Python scripts I did this already quite a while ago by introducing "triple-dash" arguments and parsing them via the standard [argparse](https://docs.python.org/2/library/argparse.html) module. See my OIB/OIF stitcher for an example (argparse code starts at [line 197](https://github.com/imcf/imcf-toolbox/blob/master/fiji/tools/FluoView_OIF_OIB_Stitcher.py#L197)):

https://github.com/imcf/imcf-toolbox/blob/master/fiji/tools/FluoView_OIF_OIB_Stitcher.py

**Comment by ctrueden** [comment]
@hinerm Thanks for writing those docs.

In the final section, you mention that "user parameters" should be declared first. I think this is an unnecessary restriction. We should rework your arg parsing code to apply to only _unresolved_ inputs at the appropriate point in the module preprocessing pipeline. Then it will automagically skip parameters like services.

**Comment by hinerm** [comment]
>We should rework your arg parsing code to apply to only unresolved inputs at the appropriate point in the module preprocessing pipeline.

My first thought on how to do this is to standardizing the parameter parsing in the `ModuleService` and separate mapped and unmapped parameters. Mapped parameters have to be assigned before preprocessing, while unmapped are assigned after preprocessing but before running.

Also, since we'll need to do *some* input assignments in the `ModuleRunner`, I think we should move *all* input handling there.

**Comment by ctrueden** [comment]
> Mapped parameters have to be assigned before preprocessing, while unmapped are assigned after preprocessing but before running.

Sorry, I don't understand. There is no such thing as "after preprocessing but before running." Rather, you can just make a preprocessor that operates at the appropriate juncture of the preprocessing pipeline.
