### ISSUE TITLE
Scaling images corrupts arrow overlays

### ISSUE THREAD

**Issue by Sethur** [imagej/ImageJ#125]
OS: Windows 10 x64
Java: OpenJDK Runtime Environment (Zulu 8.54.0.22-SA-win32) (build 1.8.0_292-b10)
ImageJ: 1.53k

**Reproductive steps:**

1. Draw an arrow somewhere in the image via the default button bar arrow tool:
![image](https://user-images.githubusercontent.com/2142589/131495885-358ad7aa-b44c-472e-becf-c3893d80f4a8.png)
![image](https://user-images.githubusercontent.com/2142589/131496106-588c4291-c721-4576-b3d8-08c9cf6c0c50.png)
2. Add the arrow to the overlay
3. Scale the image to a factor of 2.0 in the x- and y-directions via `Image->Scale...`

**Issue**
The arrow head is missing in the scaled image.
![image](https://user-images.githubusercontent.com/2142589/131496365-c3a899b3-220b-4fec-b6af-5533bb47dcc0.png)

**Expected behavior**
The arrow head should be present in the scaled image.

**Comment by justinjconroy** [comment]
This is a bug in the scale method of RoiScaler.java. It assumes all Line Roi's are simple lines. I have just initiated a pull request with the fix for this.

**Comment by Sethur** [comment]
Fixed with @justinjconroy 's pull request.
