### ISSUE TITLE
Add a "Recent changes" link to imagej.net Tools menu

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej#133]
The Fiji site (http://fiji.sc/) has a "Recent changes" link under its Tools menu. But the ImageJ site (http://wiki.imagej.net/) does not. Probably skin-specific?

As [requested on the forum](http://forum.imagej.net/t/structuring-ij-developer-wiki/28/26) by @tferr, we want http://imagej.net/ to also show a "Recent changes" link.

**Comment by ctrueden** [comment]
I switched to a new skin, and added the Recent changes link to the rightmost column's list of tools. I hope you like it!

**Comment by tferr** [comment]
Looks Great! thanks!
