### ISSUE TITLE
Licenses link from Help menu is broken

### ISSUE THREAD

**Issue by ChrisWeisiger** [imagej/imagej#138]
Help menu -> Licenses tries to load the page at http://fiji.sc/cgi-bin/gitweb.cgi?p=fiji.git;a=blob_plain;f=LICENSES;hb=HEAD which 404s.

**Comment by imagejan** [comment]
This is in the obsolete [Fiji_Updater](https://github.com/fiji/Fiji_Updater) project:
https://github.com/fiji/Fiji_Updater/blob/master/src/main/resources/plugins.config

`Fiji_Updater.jar` is still served by the Fiji update site, maybe it could be removed?

**Comment by ctrueden** [comment]
Thanks for the report, @ChrisWeisiger!

I fixed the `fiji.sc` server configuration so these old URLs redirect properly to the correct location.

I will now clean up the Help menu for ImageJ2. Stay tuned.
