### ISSUE TITLE
RoiManager: Create Mask only takes one single ROI

### ISSUE THREAD

**Issue by Meyenhofer** [imagej/imagej#143]
version: 1.51d

Steps:
1) Open an image
2) draw at least 2 ROI's and add each to the RoiManager
3) select all (shift click, since the select all button seems to have disappeared)
4) Edit > Selection > Create Mask

Here only the first roi will be put into the mask image, all the other roi's are ignored.
I seem to recall that this was not the case some time ago. It obviously makes sense to include all the selected roi's in the mask image

**Comment by ctrueden** [comment]
I tested with ImageJ 1.51d, 1.50i and 1.49v and they all have the same behavior: selecting multiple ROIs in the ROI Manager does _not_ create an OR-ed selection of those ROIs on the active image. Only one of the ROIs becomes the selection.

You can click the ROI Manager's More button and OR the selected ROIs, though, and then select that one to make it the selection on the active image. Then create a mask of that.

I am closing this issue. But if you identify a specific older version of ImageJ that has the behavior you seek, and believe this change was a regression, feel free to reopen it.
