### ISSUE TITLE
Bug in AutoThresholder / Minimum algorithm?

### ISSUE THREAD

**Issue by FiReTiTi** [imagej/imagej#144]
Hi,
I was looking into the AutoThresholder.Minimum method code, and I've noticed something that does not make sense, starting at the line 635:

	double [] tHisto = iHisto;
	while (!bimodalTest(iHisto) ) {
		//smooth with a 3 point running mean filter
		for (int i=1; i<255; i++)
			tHisto[i]= (iHisto[i-1] + iHisto[i] +iHisto[i+1])/3;
		tHisto[0] = (iHisto[0]+iHisto[1])/3; //0 outside
		tHisto[255] = (iHisto[254]+iHisto[255])/3; //0 outside
		iHisto = tHisto;

 - First the line `double [] tHisto = iHisto;` is just a pointer affectation, not a copy. And then in the loop, we have the opposite `iHisto = tHisto;`. This pointer affectation followed by the opposite affectation does not have any sense.
 - Second, a smoothing is performed into the while loop. But the result in put into tHisto (for example `tHisto[i]= (iHisto[i-1] + iHisto[i] +iHisto[i+1])/3;`), but we've seen before that `double [] tHisto = iHisto;`. So the result is in fact put directly into the original array. When doing a smoothing, the result has to be stored into a separated array.

I think that a bug and it comes from a misunderstanding of the MatLab code. I guess that MatLab duplicates the code when doing an affectation like in the first line.

Am I wrong?

**Comment by imagejan** [comment]
This affects all of:
https://github.com/imagej/imagej1/blob/ce491f23ca56a342576ee13455de60bf018b1015/ij/process/AutoThresholder.java#L635

https://github.com/fiji/Auto_Threshold/blob/master/src/main/java/fiji/threshold/Auto_Threshold.java#L890

and

https://github.com/imagej/imagej-ops/blob/master/src/main/java/net/imagej/ops/threshold/minimum/ComputeMinimumThreshold.java#L92

Maybe @landinig and @rasband can comment.

**Comment by FiReTiTi** [comment]
Thanks, I didn't investigate further than this method. And indeed, the issue seems to be the same. If I am right, then a simple fix would be:

    double[] tHisto = new double[iHisto.length] ; // Instead of double[] tHisto = iHisto ;

and

    System.arraycopy(tHisto, 0, iHisto, 0, iHisto.length) ; //Instead of iHisto = tHisto ;

**Comment by rimadoma** [comment]
I didn't debug the code, but it seems to me the algorithm is performed "in place" to avoid creating another array. In the the while loop the last line is `iHisto = tHisto`, so on the next round the code will operate on the results of the previous round.

Example:
1st round
`iHisto = {0, 1, 2, 3}`
`tHisto = {0.34, 1, 2, 1.67}`
2nd round
`iHisto = {0.34, 1, 2, 1.67}`
`tHisto ={0.44, 1.111, 1.56, 1.22}`

and so forth

**Comment by FiReTiTi** [comment]
Unfortunately, it's not what is happening. `double [] tHisto = iHisto;` means that tHisto has the same pointer as iHisto, so they point exactly on the same array, so they share the same values.

Here is a little test I just made using 6 values from 0 to 5, and performing a single iteration. Obviously I displayed the values before `iHisto = tHisto;`, but it does not change anything according to what I've written previously.

iHisto: 0.3333333333333333 1.0 2.0 3.0 4.0 3.0
tHisto: 0.3333333333333333 1.0 2.0 3.0 4.0 3.0

**Comment by landinig** [comment]
Hi thanks for looking into this.
Shouldn't it be:
```
double[] tHisto = new double[iHisto.length] ; 
System.arraycopy(iHisto, 0, tHisto, 0, iHisto.length) ;
```
then in the loop as you say:
`System.arraycopy(tHisto, 0, iHisto, 0, iHisto.length) ; //Instead of iHisto = tHisto ;`

Now:
AuPbSn40.jpg Minimum: 127
blobs.gif Minimum: 124
boats.gif Minimum: 68
bridge.gif Minimum: 210
lena-std.tif Minimum: 74

Before:
AuPbSn40.jpg Minimum: 127
blobs.gif Minimum: 124
boats.gif  Minimum: 67 <-- different
bridge.gif Minimum: 210
lena-std.tif Minimum: 74

**Comment by FiReTiTi** [comment]
@landinig: that's almost the solution I proposed few comments before.
Except that you don't need the first System.arraycopy (the one juste after tHisto declaration), because tHisto will be filled with the computed values, and it will be only read to fill iHisto.

**Comment by FiReTiTi** [comment]
Btw, if we use `iHisto.lenght-1` (or `data.length-1`)instead of 255, then the code works also for ShortProcessor

**Comment by landinig** [comment]
Actually that '255' is in the adapted version included in ImageJ, the original plugin (in my page) and the one in Fiji already support 16 bit.

**Comment by FiReTiTi** [comment]
Ok, it would be great to upgrade that ImageJ code.
Could you please point me the FiJi source code for this class, I didn't find it in the git.

**Comment by landinig** [comment]
Sure, it is:
https://github.com/fiji/Auto_Threshold/blob/master/src/main/java/fiji/threshold/Auto_Threshold.java

**Comment by landinig** [comment]
Wait a minute before changing it, please I am checking something.

**Comment by FiReTiTi** [comment]
Thanks for the link. And indeed, this issue seems to be the same on FiJi.
Btw, why is FiJi more advanced than ImageJ? At least for this type of details.

**Comment by imagejan** [comment]
> Could you please point me the FiJi source code for this class, I didn't find it in the git.

I linked to all three derivations of this code in my post above.

**Comment by FiReTiTi** [comment]
@imagejan: thanks and sorry, I didn't notice that it also included the FiJi source code.

**Comment by landinig** [comment]
It has to do with how the auto thresholds were incorporated into Fiji and IJ.
I ported a number of methods into the plugin existing in my page. This was added to Fiji and changed to support 16bits by Johannes.
At the same time Wayne included the methods in IJ, but the way IJ works on 16 bit images is different, so the code is ported, not identical.
If Wayne is not reading this, it might be an idea to drop him a note.

Go ahead to fix the Fiji code, if you wish.
Thanks again.

**Comment by landinig** [comment]
@FiReTiTi I already emailed Wayne about this. Do you want to push a commit to fix this in the Fiji repo? If not I can do it tomorrow.

**Comment by FiReTiTi** [comment]
Ok, done for the two last links, but not for the first link ImageJ (https://github.com/imagej/imagej1/blob/ce491f23ca56a342576ee13455de60bf018b1015/ij/process/AutoThresholder.java#L635).

**Comment by landinig** [comment]
OK, let's ask @imagejan or @ctrueden if they kindly help: 
@FiReTiTi  has forked the code and fixed it. How does the commit get sent to the master?
https://github.com/FiReTiTi/Auto_Threshold/commit/6c2083b9c21897601027717493fca40bd2fc132d

**Comment by landinig** [comment]
@FiReTiTi I remember it now, @imagejan mentioned it recently: Open a pull request. 
https://help.github.com/articles/creating-a-pull-request/ 
Go to the Pull request tab and create a new one.

**Comment by FiReTiTi** [comment]
@landinig : everything I could change should be pushed now.
Thanks for your help.

**Comment by landinig** [comment]
@FiReTiTi  Thank you for spotting it an fixing it. I added a little comment in the header thanking you too.

**Comment by imagejan** [comment]
All three code location have been fixed:
ImageJ1: https://github.com/imagej/imagej1/commit/031cbd239c89d5acb9038db86f3d1953a9604048
Fiji: https://github.com/fiji/Auto_Threshold/pull/6
ImageJ-Ops: https://github.com/imagej/imagej-ops/pull/423

Closing this now.
