### ISSUE TITLE
How to add CJK characters on image?

### ISSUE THREAD

**Issue by yeqibin** [imagej/imagej#147]
Adding CJK characters is not supported in ImageJ. Is there a way to do that?

**Comment by imagejan** [comment]
The following IJ1 macro works for me:
```
run("Blobs (25K)");
drawString("お元気ですか?", 10, 80);
```

What doesn't seem to work is directly typing or pasting CJK symbols into text selections. I suggest contacting `@Wayne` on the [forum](http://forum.imagej.net/) regarding this.

**Comment by yeqibin** [comment]
It works. Thank!
