### ISSUE TITLE
Save Options permanently

### ISSUE THREAD

**Issue by francwalter** [imagej/ImageJ#148]
Hallo

I have ImageJ 1.53o on Mac OS 10.11.6 with java 15.0.1 2020-10-20 (build 15.0.1+9-18).

I use ImageJ mostly just to mark screenshots with red rectangles for explanations. 
But every time I open ImageJ I have to set the foreground color again to red, in: Edit > Options > Colors.
I don’t find any global settings menu in ImageJ, only this menu under Edit, which makes me think it is not meant as real preferences menu, just for the actual file.

Is there a way to save such presets permanently?
Thanks, frank

**Comment by mutterer** [comment]
Hi, 
you can record the "Colors..." command and paste the output into the Edit>Options>Startup dialog to have it run automatically each time you start ImageJ.

run("Colors...", "foreground=black background=white selection=red");

Jerome.

**Comment by francwalter** [comment]
Jes, this works, thank!

Edit > Options > Startup...

`run("Colors...", "foreground=red background=white selection=red");`

sets the foreground-color to red 😄 
But I wonder why it is not possible to save options permanently, is there a reason?
Every application can do this!
Thanks

**Comment by mutterer** [comment]
It is saved in the preferences file in my case.
The preferences file is here for me:
  IJ.getDir("preferences"): /Users/jmutterer/Documents/ImageJ.app/
In the IJ_Prefs.txt file, you can find an entry that looks like this: 
roicolor=\#FF0000

**Comment by francwalter** [comment]
`IJ.getDir("preferences")`

where can I run such a command? I dont find that.
I have no ImageJ.app directory :(

**Comment by mutterer** [comment]
Hi! sorry I wasn't clear.
You can see the output of this command when running Plugins>Utilities>ImageJ Properties
or
you can run the following macro: eval('script','IJ.getDir("preferences");');

**Comment by francwalter** [comment]
Ah, OK, thanks!
I found it now in the ImageJ Properties window :)

`IJ.getDir("preferences"): /Users/f/Library/Preferences/`

In IJ_Prefs.txt I can read:

<details>
  <summary>IJ_Prefs.txt</summary>

´´´
#ImageJ 1.53o Preferences
#Mon Jan 24 10:10:35 CET 2022
new.fill=0
.arrows.loc=513,135
pp.options=0
recent09=/Users/f/Desktop/2013-08-20_15.29.45.jpg
recent08=/Users/f/Desktop/Bildschirmfoto 2014-06-14 um 11.22.19.png
recent07=/Users/f/Desktop/Bildschirmfoto 2015-02-19 um 12.23.39.png
recent06=/Users/f/Desktop/Bildschirmfoto 2015-02-24 um 10.31.52.png
bcolor=\#FFFFFF
recent05=/Users/f/Desktop/Bildschirmfoto 2015-02-25 um 23.01.42.png
recent04=/Users/f/Desktop/IMG_0651.jpg
recent03=/Users/f/Desktop/Bildschirmfoto 2015-10-06 um 17.34.25.png
recent02=/Users/f/Desktop/WhatsApp Image 2016-08-28 at 17.39.38.jpeg
noise.sd=25.0
recent01=/Users/f/Desktop/photo5420300147356708398.jpg
recent00=/Users/f/Desktop/SelectIconPack.jpg
.toolbar.brush.size=15
raw.offset=0
fcolor=\#FF0000
raw.width=512
pp.fontsize=14
.manager.loc=521,117
prefs.options=1073758208
new.height=400
measurements=19
showcolor=\#00FFFF
fps=7.0
plugin00=h,"*Copy to System[Y]",ij.plugin.Hotkeys("Copy to System")
.brush.overlay=false
raw.height=512
.fonts.loc=500,133
jpeg=75
.brush.loc=488,171
.toolbar.tool06=Arrow Tool
.line.loc=478,186
ij.y=23
.toolbar.tool05=Arrow Tool
ij.x=294
.toolbar.tool04=Arrow Tool
new.slices=1
.toolbar.tool03=Pencil Tool
menu.size=0
pp.height=340
raw.n=1
new.type=0
div-by-zero=Infinity
raw.options=0
pp.width=600
recent14=/Users/f/Desktop/b5vOF4Y2Sr4iiHadbiFTTI.jpg
new.width=400
recent13=/Users/f/Desktop/Screenshot_2013-05-01-07-53-06.png
recent12=/Users/f/Desktop/Screenshot_2013-05-01-07-53-28.png
recent11=/Users/f/Desktop/Bildschirmfoto 2013-06-03 um 12.26.48.png
recent10=/Users/f/Desktop/Bildschirmfoto 2013-06-03 um 12.29.03.png
raw.gap=0
prefs.options2=0
precision=3
roicolor=\#FF0000
ap.options=64
dir.image=/Users/f/Desktop/
.pencil.width=1
raw.type=0

´´´
</details>

the roicolor is red here, but I had the Macro running already. I deleted the macro and still it is red!?
I dont know what happened.
Seems to work now, most likely some misconfiguration at my end, so I close this issue, which isnt a ImageJ issue and 
**THANK YOU** for your very nice and good help!
frank
