### ISSUE TITLE
Missing NullCheck in PlotWindow.java line 720

### ISSUE THREAD

**Issue by krami79** [imagej/imagej#149]
I just stumbled across this error message when closing a live PlotWindow in ImageJ 1.51g

```
Exception in thread "Live Profiler" java.lang.NullPointerException
	at ij.gui.PlotWindow.run(PlotWindow.java:720)
	at java.lang.Thread.run(Thread.java:662)
```

I am not an ImageJ dev, but this new line should do the trick:
```java
Plot plot = plotMaker!=null?plotMaker.getPlot():null;
```

**Comment by imagejan** [comment]
All the `ij.*` classes are part of https://github.com/imagej/imagej1/, but maybe @rasband reads it here, too?

**Comment by krami79** [comment]
thanks for pointing that out I recreated the issue at ImageJ1. can be closed here

**Comment by ctrueden** [comment]
Thanks @krami79. For proper cross-referencing: the new issue is imagej/imagej1#24.
