### ISSUE TITLE
Image Calculator, substract when first image is displayed using an inverted LUT

### ISSUE THREAD

**Issue by effepivi** [imagej/imagej#150]
If I have two images, I1 and I2,
and if I1(x,y)=255,
and if I1 is displayed with an inverted LUT, then
I1-I2=I2.

My understanding is that the LUT is only for the visualisation and should not affect the calculation. The result is shown using an inverted LUT, which might be confusing.

**Comment by ctrueden** [comment]
@rasband Any thoughts?

**Comment by rasband** [comment]
The following test macro works as expected. The output image is not the same as the second image ("i2"). 

  run("Close All");
  newImage("i1", "8-bit white", 512, 512, 1);
  run("Invert LUT");
  newImage("i2", "8-bit black", 512, 512, 1);
  run("Add...", "value=100");
  imageCalculator("Subtract create", "i1","i2");

**Comment by effepivi** [comment]
Thanks for your replies. Maybe I should not have posted it as a bug, as it might be more a question/comment (I am new to github).

Below is what I did. The numerical values of the computed image are fine, but it is displayed using an inverted LUT. Is it intended that the resulting image inherits of the LUT of the left operand in Image Calculator?
Using the various operations of Image Calculator the LUT might lose it meaning, no?



run("Text Image... ", "open=[/Users/fpvidal/Documents/img_0014.mat]");
newImage("Untitled", "32-bit white", 726, 460, 1);
run("Add...", "value=255");

imageCalculator("Subtract create 32-bit", "Untitled","img_0014.mat");
selectWindow("Result of Untitled");

**Comment by imagejan** [comment]
> Maybe I should not have posted it as a bug, as it might be more a question/comment (I am new to github).

Indeed, a more appropriate place for this might be the [ImageJ forum](http://forum.imagej.net/).

> The numerical values of the computed image are fine

Alright. Your original comment suggested something different.

> Is it intended that the resulting image inherits of the LUT of the left operand in Image Calculator?

Well, the resulting image has to have _some_ LUT, right? And in many cases, inheriting from the first operand is simply the best guess (i.e. following the principle of least surprise). I don't see why e.g. the `Grays` LUT should have any preference over a more quantitative LUT like `mpl-viridis`, or Color LUTs when you're working with false-colored channels.

But maybe @rasband has more comments?

As there's nothing wrong numerically (and it's a [ImageJ 1.x](https://github.com/imagej/imagej1/) topic), I'm closing this issue.
