### ISSUE TITLE
Incorrectly calculated coordinates of spline ROI

### ISSUE THREAD

**Issue by sskokic** [imagej/ImageJ#151]
I recently discovered that, even though ROI points set by the user in ImageJ have sub-pixel precision, the area inside the ROI is calculated by counting whole pixels that are in some way determined to be inside the ROI.

As troubling as that is (what is the point of this additional precision if it is not used later on?), I thought, nevermind, I will write my own function that will calculate the area inside the polygon from the ROI edge coordinates supplied via command Roi.getCoordinates. 

Then I discovered that the **coordinates provided by Roi.getCoordinates function did not lie on the ROI outline**. Some of them fall inside while others fall outside the selected area, and this happens in batches. Kind of as if some Fourier series approximation was happening in the background. 

I first discovered this on a brain scan image, but it happens even in the simplest case possible - see attached IJ macro and the output image.

This behaviour is very odd, because apparently the points of the ROI used for drawing the ROI when the user manipulates user-defined points are calculated with one function, and then getCoordinates uses some other function and gives some other coordinates.

From the looks of it, the roi.getCointainedPoints function, which agrees 100% with calculated ROI area when using "Measure" command, fits better with the drawn ROI outline than with the points calculated via Roi,getCoordinates. So my guess is that there is something incorrect in the Roi.getCoordinates function.

This is a very serious issue because it turns out that you cannot trust what you see (or draw) in ImageJ. Not to mention the big fresh question mark above all segmentation results performed in it. Fortunately, the deviation seems to at least partially compensate for itself when going around the ROI. However, there shouldn't be any error at all. The Roi.getCoordinates function should simply read the numbers out from wherever they are calculated in real time when manipulating user points.

Has anyone come across this already? Can you look into this matter and hopefully fix it? I have attached the IJ macro and the image demonstrating the issue.

Thanks to all,

Sinisa 

[ROI_EDGE_COORDINATES_TEST.zip](https://github.com/imagej/ImageJ/files/8023321/ROI_EDGE_COORDINATES_TEST.zip)
![Smooth_ROI_edge_comparison](https://user-images.githubusercontent.com/99037974/152977868-21704467-f56d-40ba-ac05-0d1e265a4e70.JPG)

**Comment by rasband** [comment]
The coordinates are on the outline but  they are displayed at pixel centers so they are offset by (0.5,0.5). You can have the points displayed on the outline by subtracting 0.5, as in the example below.

This issue is discussed on the forum at:

https://forum.image.sc/t/why-are-some-roi-overlays-are-being-shifted-when-saving-a-hyperstack-to-tiff-and-opening-it-in-imagej/62192

```
newImage("TEST", "8-bit black", 200, 200, 1);
makePolygon(25,25,125,25,125,125,25,125);
run("Fit Spline"); 
Overlay.addSelection("red");
Roi.getCoordinates(xpoints, ypoints); 
for (i=0; i<xpoints.length; i++) {
    xpoints[i] -= 0.5;
    ypoints[i] -= 0.5;
}
makeSelection("point", xpoints, ypoints);
Overlay.addSelection("white");
Roi.remove;
run("Set... ", "zoom=1500 x=8 y=57");
```
![Screenshot](https://user-images.githubusercontent.com/1633637/153066691-302a322b-c9c0-4fcd-8a05-27201f404df5.png)
