### ISSUE TITLE
32bpp RGB photo in Fiji

### ISSUE THREAD

**Issue by arangel1013** [imagej/ImageJ#153]
<img width="1148" alt="Screen Shot 2022-02-25 at 2 04 13 PM" src="https://user-images.githubusercontent.com/63241148/155773036-55972bed-51b9-4f4f-a4fa-1dc2f97dccc1.png">
<img width="699" alt="Screen Shot 2022-02-25 at 2 05 03 PM" src="https://user-images.githubusercontent.com/63241148/155773166-4e4d1d7b-181a-4b33-ba19-944ff1452d44.png">
<img width="640" alt="Screen Shot 2022-02-25 at 2 13 52 PM" src="https://user-images.githubusercontent.com/63241148/155774259-7b5c19fa-29bd-4eb9-bf21-6769d34ce51b.png">
 I'm opening these large files in Fiji but they don't appear accurately.. One screenshot is when I open the image in Fiji, one is the preview of the original image, and the other screenshot is the info. Any suggestions?

**Comment by rasband** [comment]
Please upload the original image, or a smaller image that also exhibits the problem.

Do you see the problem when you open the image using Bio-Formats (File>Import>Bio-Formats)?

**Comment by arangel1013** [comment]
I don't see the problem using Bio-Formats. After you mentioned it, I downloaded the plugin and now I can see the images on Fiji. Thank you so much
