### ISSUE TITLE
Updating Jython to version 2.6

### ISSUE THREAD

**Issue by srikanthbojja** [imagej/imagej#153]
Jython version shipped with current IJ is 
`2.5.3 (2.5:c56500f08d34+, Aug 13 2012, 14:54:35) 
[Java HotSpot(TM) 64-Bit Server VM (Oracle Corporation)]
`
is it possible to upgrade the jython to 2.6?

**Comment by imagejan** [comment]
> is it possible to upgrade the jython to 2.6?

The 0.4.0 version of the [`scripting-jython`](https://github.com/scijava/scripting-jython) repo already depends on [`jython-shaded 2.7.0`](https://github.com/scijava/jython-shaded), so I guess it is just a matter of uploading the artifacts to the Java-8 update site.

I don't recall if there were any issues with Fiji installations on Java 6 that were blocking this. @ctrueden any comments?

I can test if needed.

**Comment by srikanthbojja** [comment]
Great. If there are no issues, please push the update.

**Comment by imagejan** [comment]
@srikanthbojja you can already use and test the newer version by downloading these artifacts from the maven repository:

* http://maven.imagej.net/service/local/repositories/central/content/org/scijava/jython-shaded/2.7.0/jython-shaded-2.7.0.jar
* http://maven.imagej.net/service/local/repositories/releases/content/org/scijava/scripting-jython/0.4.0/scripting-jython-0.4.0.jar

dropping them into your `./Fiji.app/jars` folder, deleting the older versions, and restarting Fiji.
Please report here if you encounter any issues.

**Comment by ctrueden** [comment]
We did recently migrate from 2.5.3 to 2.7.0 of Jython, but there are some niggling issues with the dependency tree which result in Fiji selecting 2.5.3. If you look at the dependency tree of this repository (`imagej/imagej`), actually Jython 2.7.0 _is_ selected. But for `fiji/fiji` it is not. Unfortunately, I do not have time to fix immediately, but I will work on resolving it at the end of this month, or in early January.

**Comment by srikanthbojja** [comment]
@ctrueden I am using Fiji and shall wait for the fix.

**Comment by hadim** [comment]
I think this is fixed now.

**Comment by ctrueden** [comment]
@hadim I think you are right; thanks! Not sure when it started behaving properly, though...
