### ISSUE TITLE
Inconsistent B&C behavior across Z-project functions

### ISSUE THREAD

**Issue by renesayshi** [imagej/imagej#154]
Hi! I hope someone can help; there must at least be an easy workaround for my problem.
Sample data is X/Y and time, 520 slices. I want to generate projections of 20 slices from different intervals. A "grouped Z project" generates projections of the correct intensity but wrong intervals; a "Z project" generates correct intervals with wrong (auto-adjusted) intensities.
Sample data: https://www.dropbox.com/s/bh1f9qkiopgsttj/Image44.tif?dl=1

Scenario 1:
- open image
- Image - Stacks - Tools - Grouped Z Project
- Select "Sum Slices", specify Group size "20" (To project 20 slice substacks)
- OK
- optional: Duplicate individual slices 1 and 2 for comparison with scenario 2

Scenario 2:
- open image
- Image - Stacks - Z Project
- Specify start slice "1", stop slice "20"
- Select Projection type "Sum Slices"
- OK
- repeat with start slice "21", stop slice "40"

Comparing the results of scenario 1 and 2, it is clear that B&C were changed in scenario 2. Using "Auto contrast" changes the results from scenario 1 to look almost like scenario 2. I however would like to maintain the unmodified contrast of scenario 1 with different projections, like slices 155-174.
Is the behavior I describe here intended, and if so, is there a workaround for my situation?

Thank you for your attention,
rene

**Comment by ctrueden** [comment]
This is an ImageJ1 question. @rasband Thoughts?

**Comment by rasband** [comment]
Grouped Z Project "Sum Slices" appears to not work very well with 8-bit stacks. You can work around the problem by converting the stack to 16-bits before running Grouped Z Project.

**Comment by rasband** [comment]
Grouped Z Project "Sum Slices" does work as expected with 8-bit stacks, as it generates a 32-bit stack. I had mistakenly used "Average Intensity", which generates an 8-bit stack. It is expected that the display ranges in the two scenario will be different except for the first group. The display range resulting from using the Z Project command on slices 155-174 is based on the pixel value range of the sum of slices 155-174. The display range resulting from using Grouped Z Project is based on the pixel value range of the sum of slices 1-20.

**Comment by renesayshi** [comment]
Thank you for your explanations! I think that my confusion arose because the 16-bit original (actually a 12-bit original) was converted to a 32-bit projection. The original was of acceptable quality when displaying the entire 16-bit range, the 32-bit is not; so it is good that ImageJ adjusts the display range for the result, be it a single image or a stack, but this led to my confusion.
