### ISSUE TITLE
Inconsistent origin updates

### ISSUE THREAD

**Issue by bogovicj** [imagej/ImageJ#155]
@rasband,

Cropping / duplicating an image sometimes updates the origin metadata, but sometimes does not.

From what I can tell, it does not update the origin when it is set to zeros, but do update it otherwise.  

I would expect the origin to always be updated.

## To reproduce

Running this macro

```
run("MRI Stack");
run("Properties...", "channels=1 slices=27 frames=1 pixel_width=1.0000 pixel_height=1.0000 voxel_depth=1.0000 origin=-5,-10,-20");
makeRectangle(51, 67, 84, 100);
run("Duplicate...", "duplicate");
selectWindow("mri-stack-1.tif");
getImageInfo()
```

sets the image origin to some non-zero value, then crops ("Duplicate"s with an ROI).
It logs some output, one line of which is:

```
Coordinate origin:  -56,-77,-20
```
This is correct, and what I would expect.

Running this macro (same as above but does not set the origin)

```
run("MRI Stack");
makeRectangle(51, 67, 84, 100);
run("Duplicate...", "duplicate");
selectWindow("mri-stack-1.tif");
getImageInfo()
```

also logs some output, one of of which is:

```
Coordinate origin:  0,0,0
```

I expect a non-zero origin in this latter situation as well, because the origin when it is opened is `0,0,0`

**Comment by rasband** [comment]
When duplicating a selection, the origin is only updated if it is not set to zero in the source image. You can force it to be updated by setting the x origin to small non-zero value like 0.00001. Here is an example:

```
run("MRI Stack");
run("Properties...", "origin=0.00001,0,0");
makeRectangle(51, 67, 84, 100);
run("Duplicate...", "duplicate");
selectWindow("mri-stack-1.tif");
getImageInfo();
```

**Comment by bogovicj** [comment]
@rasband 
Why is this the desired behavior?

**Comment by rasband** [comment]
_Why is this the desired behavior?_

This is the way it has always worked and it can't be changed without breaking existing workflows.

**Comment by odinsbane** [comment]
@rasband 

What about changing the origin when an image is scaled? It seems like the origin should be scaled to the destination image pixels. Would that also break workflows?

**Comment by NicoKiaru** [comment]
> This is the way it has always worked and it can't be changed without breaking existing workflows.

Which ones ? Can we work on these ? Alternatively could other fields be added in the calibration that would behave differently ? A calibrated 3D matrix to specify the location of the image in 3D would be very useful.
