### ISSUE TITLE
Deleting duplicate plugins (ij.plugin.ClassChecker)

### ISSUE THREAD

**Issue by imagingbook** [imagej/ImageJ#156]
`ClassChecker` "_checks for duplicate class and JAR files in the plugins folders and deletes older duplicates_": I am not sure about the original purpose of this, since duplicate `.class` and `.jar` files cannot exist unless they reside in different packages. That is, plugins with the same names but in different packages should be allowed in general. If duplicate "command names" are a problem, the package names could be included.

_Apart from this_, there appear to be **2 issues** with `ClassChecker` as it is now:

1. Deletion does not work properly. Assume there are 3 plugins with the same name `My_Inverter.class` in three packages `A`, `B`, `C`, with identical modification dates. In this case, only `A.My_Inverter.class` is deleted, but **3 times** in a row:
<pre>
Deleting duplicate plugin: D:...\ImageJ\plugins\A\My_Inverter.class
Deleting duplicate plugin: D:...\ImageJ\plugins\A\My_Inverter.class
Deleting duplicate plugin: D:...\ImageJ\plugins\A\My_Inverter.class
</pre>

2. Compiled `package-info.class` files should be ignored, since they cannot contain plugin code. They should be allowed to exist, there is no reason to delete them at all:
<pre>
Deleting duplicate plugin: D:...\ImageJ\plugins\A\package-info.class
Deleting duplicate plugin: D:...\ImageJ\plugins\A\package-info.class
</pre>

**One more issue:** The deleted `.class` files get nevertheless listed in the `Plugins` menu, so when a user selects any of these a "class-not-found" error occurs!

**Comment by rasband** [comment]
Hi Wilhelm,

Do you any suggestions for how the ClassChecker can be modified to fix these issues?

**Comment by imagingbook** [comment]
Sure, I'd be happy to fix it but I am still unclear about its intent. Apparently ClassChecker is supposed to find plugins with identical names in (evidently) different packages and delete all but the most recent .class file. 
- I find the idea of purging .class files a bit irritating and do not see why deletion of duplicates is necessary at all.
- What happens if plugins with identically named plugins are loaded from a JAR file? Seems in this case ClassChecker can't do anything.
I tried to run ImageJ with ClassChecker completely deactivated and it seems to be doing just fine. So perhaps it could be removed all together, or I have overlooked something?

**Comment by rasband** [comment]
The ImageJ 1.53r6 daily build deactivates ClassChecker except when the Compile and Run command is used.

**Comment by rasband** [comment]
The ClassChecker in the ImageJ 1.53s7 daily build displays warning messages but no longer deletes files. It only runs when you use the Compile and Run command, which typically creates class files that are not in a package.

**Comment by imagingbook** [comment]
I cannot see this change in this repo. Has the 1.53s7 build been pushed?

**Comment by rasband** [comment]
The new 1.53s10 commit has all the ClassChecker changes.
