### ISSUE TITLE
Bug in Rotate function in Fiji

### ISSUE THREAD

**Issue by DentedDuck** [imagej/ImageJ#157]
Hi, 
   The rotate image function (Image --> Transform --> Rotate) seems to have a bug when the enlarge image option is checked. If no rotation is specified (Angle = 0), then the image increases in height by one pixel. If angle = 90, then the width increases by one pixel. No change in height is expected in either case. 

ImageJ v 1.53q under Fiji. Running on Win10. 

Thanks, 

Dave

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.53s10 daily build.
