### ISSUE TITLE
What is the difference between this and the NIH version?

### ISSUE THREAD

**Issue by rogersachan** [imagej/imagej#158]

**Comment by dietzc** [comment]
Hi @rogersachan,

please find more information here:

* https://imagej.net/ImageJ2
* https://arxiv.org/abs/1701.05940
* Readme of https://github.com/imagej/imagej

Hope that helps,

Christian

**Comment by rogersachan** [comment]
This only describes the program, not the difference between this and the one on https://imagej.nih.gov/ij/






On Wed, Feb 1, 2017 at 8:26 PM -0500, "Christian Dietz" <notifications@github.com> wrote:












Hi @rogersachan,


please find more information here:

https://imagej.net/ImageJ2
https://arxiv.org/abs/1701.05940
Readme of https://github.com/imagej/imagej



Hope that helps,


Christian

**Comment by imagejan** [comment]
@rogersachan maybe this overview helps: http://imagej.net/ImageJ#Flavors

In short, the NIH ImageJ 1.x is mirrored in https://github.com/imagej/imagej1/ and transformed in a maven-compatible way here: https://github.com/imagej/ImageJA/. The Fiji distribution bundles both ImageJ1.x and ImageJ2 (i.e. this here repository).

If you were missing this information on the [wiki](http://imagej.net/ImageJ), please improve it by editing the page yourself.
