### ISSUE TITLE
Unable to use ITCN_Runner through javascript (Possible Bug in the Plugin .jar file)

### ISSUE THREAD

**Issue by lune3141** [imagej/imagej#159]
Hi Everyone, 

I am trying to use the ITCN plugin for counting the number of nuclie in my image using javascripts. My old (ImageJ 1.49xx) javascript no longer works because everything is set to Java 8 conventions for ImageJ1.51xx.  

 example code:- 

      //importing the requisite packages
      importClass(Packages.ij.ImagePlus);
      importClass(Packages.ITCN_Runner);

      var filename = 'Path/to/8bit/single/channel/Dapi/.tiff/file'
      var imp = new ImagePlus(fileName);                             //make a ImagePlus object

      var impTitle = imp.getShortTitle();
      var impPath = imp.getOriginalFileInfo().directory;

     
       //Call ITCN_runner to generate results window 

       var runner = new ITCN_Runner( imp,
		24, /* width*/
		12, /* minimum distance */
		0.5, /* threshold */
		false, /* detect dark peaks */
		null /* mask ImagePlus */ )

When I run the above script, I run into the following error:- 

        TypeError: new cannot be used with non-public java type ITCN_Runner.
	      at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
       Followed by several lines...

My guess is that this is caused because the ITCN_Runner.class in the ITCN_.jar does not specify the class ITCN_Runner as public. This was alright in Java6  but is no longer allowed in Java 8 it may seem. Is it correct to assume that within the ITCN_.jar, ITCN_Runner.class should be modified to declare this class public, Or I am making a mistake here. 

Any suggestions or workarounds welcome.

**Comment by ctrueden** [comment]
You could either:

1) Recompile `ITCN_Runner` to have a public constructor; or:

2) Use Java reflection to create the runner. Something like:

```java
ITCN_Runner.class.getConstructor(ImagePlus.class, int.class, int.class, double.class, boolean.class, ImagePlus.class).newInstance(imp, 24, 12, 0.5, false, null);
```
But the exact syntax for JavaScript probably differs slightly.

Either way, this is not an issue with ImageJ directly, so I'm closing this issue.
