### ISSUE TITLE
(Windows) command-line updater has no feedback

### ISSUE THREAD

**Issue by teknowledgist** [imagej/imagej#161]
The documentation for command-line updating claims there are a number of options for getting/setting information related to updating, but most of those don't work, or at least don't provide feedback.  Anyone using the command line is probably OK without GUI feedback, but there should be something returned in the cmd window/console.

For example, `ImageJ-win64.exe --update list-update-sites` will briefly blip on task manager indicating that something runs, but nothing is returned to the cmd window.  Similarly, `ImageJ-win64.exe --update list-updateable` returns nothing though it does create a .checksums file.

At least some of it works though because `ImageJ-win64.exe --update update` does actually update ImageJ/Fiji, although it also does not provide any feedback in the cmd window.  

I am told non-Windows systems do get information returned in their console with (at least some of) these options.

**Comment by ctrueden** [comment]
> I am told non-Windows systems do get information returned in their console with (at least some of) these options.

Yes, there is a general Windows-specific problem with Java output the console, for Java processes launched via the ImageJ launcher. Try passing the `--console` flag in addition, and see if that makes a difference. I am sorry that this flag is necessary; I think it is related to the fact that Windows has different styles of process for console vs GUI (which is also why there are both `java.exe` and `javaw.exe` on Windows). If you know more about this, and have the bandwidth to improve this in the [ImageJ Launcher](https://github.com/imagej/imagej-launcher) code, that would be much appreciated.

**Comment by teknowledgist** [comment]
the `--console` option does provide some feedback on the examples I gave, but the cmd window also appears to freeze (at the end?) requiring a `<ctrl>-C` to return to a prompt.  As I [imply in another issue](https://github.com/imagej/imagej/issues/72#issuecomment-287431206), I would like to be able to log headless updates, so a hang is a problem.

I know next-to-nothing about Java or C (#, ++?) coding, so I can't be much help, sorry.

**Comment by ctrueden** [comment]
Glad to hear that `--console` gives the feedback you desire. I am closing this in favor of the already-existing imagej/imagej-launcher#29, which discusses the general crappiness of `--console` and how it should ideally be made less crappy.

**Comment by ctrueden** [comment]
> I would like to be able to log headless updates, so a hang is a problem.

@teknowledgist One workaround might be to run the launcher with `--dry-run` once, to get the actual invocation used (really, an approximation thereof, but close enough for your purposes). Then you can invoke java with that invocation, and likely capture the output of the process successfully.
