### ISSUE TITLE
In macros, List.get("Mean"), List.get("StdDev"), etc. return string instead of float when the value is 0

### ISSUE THREAD

**Issue by Sethur** [imagej/ImageJ#161]
**Testing Environment:**
- ImageJ v1.53o
- openjdk version "11.0.14.1" 2022-02-08 LTS, OpenJDK 64-Bit Server VM Zulu11.54+25-CA (build 11.0.14.1+1-LTS, mixed mode)

**Issue**
When using
```
List.setMeasurements();
meanVal = List.get("Mean");
stdVal = List.get("StdDev");
```
on a ROI that only contains `0` in a 16-bit DICOM, `meanVal` and `stdVal` are of type string and contain `"0.0"` instead of the respective float number.

**Comment by rasband** [comment]
Use List.getValue() instead of List.get().

```
  List.setMeasurements();
  mean = List.getValue("Mean");
  std = List.getValue("StdDev");
  print("mean: "+mean);
  print("std: "+std);
```
