### ISSUE TITLE
Java Annotations don't work

### ISSUE THREAD

**Issue by Edodums** [imagej/ImageJ#162]
I'm trying to build an ImageJ/Fiji plugin.
At first I tried to use ImageJ2 and ImageJ Legacy, that didn't work :
https://forum.image.sc/t/imagej-legacy-can-be-actually-used-to-create-a-plugin-for-imagej-1-x-and-fiji/66831

Now I want to use at least Google Guice (that supports Java 8 and above) for the Dependency Injection.
I had to avoid using that, and that's a pain in the ass, because I've to write a lot of boilerplate to handle what I've could have done in 3 lines of code.

This is the ImageJ 1.x I'm using:
![Schermata 2022-05-13 alle 11 05 34](https://user-images.githubusercontent.com/11229892/168250574-bfa234e8-a3a2-4c31-8434-f470722345b8.png)

It seems also that exceptions that ImageJ could give are catched, so I don't even know what I'm doing wrong when I add annotations, without them the plugin is launched just fine.

I'll appreciate any response I'll be given.

**Comment by ctrueden** [comment]
@Edodums From your description, I am not sure what you are trying to achieve. Could you please share a sample project on GitHub, along with instructions on what goes wrong, and what you would expect to have happen instead?

**Comment by Edodums** [comment]
I'm sorry it was before my graduation and my brain cells didn't work properly 🤣 
What I was trying to do at the time was using ImageJ2 and ImageJ-Legacy libraries.
What I didn't know at the time was that for my plugin to work in the ImageJ  1.x app I needed to create an uber jar
