### ISSUE TITLE
toString(number) macro changed return value for strings

### ISSUE THREAD

**Issue by christianrickert** [imagej/ImageJ#167]
The ImageJ macro `toString("abc")` returns:

`"abc"` in ImageJ **v1.53r** (and earlier), but surprisingly
`"NaN"` in ImageJ **v1.53s**.

The change might be related to the changes announced in the [ImageJ Release Notes](https://imagej.nih.gov/ij/notes.html):

> Thanks to Stein Rorvik, fixed a bug that caused the toString(number,decimalPlaces) macro function to not work as expected.

While I prefer the current implementation (it's cleaner),
the return value for non-numeric strings should be clearly stated in the [Built-in Macro Functions](https://imagej.nih.gov/ij/developer/macro/functions.html#toString).

Originally reported here: https://github.com/fiji/fiji/issues/308.

**Comment by rasband** [comment]
This regression was fixed in the ImageJ 1.53t7 daily build.

**Comment by christianrickert** [comment]
@rasband Where can I find the source changes for this fix (diff)?

**Comment by rasband** [comment]
> Where can I find the source changes for this fix (diff)?

https://github.com/imagej/ImageJ/commit/dd2eb0ac8cecaad99ce0f0f5046731c6b8247bb7

**Comment by christianrickert** [comment]
Thank you very much!
