### ISSUE TITLE
Script Parameter Syntax does not work in ImageJ Macro Functions

### ISSUE THREAD

**Issue by avh-on1** [imagej/imagej#173]
The following ImageJ macro works as expected:
```
// @String str1
print(str1);
```
But this one does not:
```
function getParameter(){
	// @String str2
	print(str2);
}
getParameter();
```
because `str2` is undefined. It seems like the macro parser completely throws out script parameters that are inside of functions.

**Comment by imagejan** [comment]
Script parameters are always global on a script level, i.e. is doesn't make sense to define them inside a function, as they're parsed before executing the actual script code.

Also, the legacy syntax (`// @String str`) you're using will only work at the script header, until the first line that isn't a parameter declaration. With the updated syntax (`#@ String str`), you can define parameter on any (non-indented) line anywhere in the script, but they still will be parsed globally before script execution.

If you want a set of parameters defined dynamically (e.g. only if a certain condition is met), you'll have to create another script and call it from your first script (using `run()` in IJ1 macro or using the ScriptService in any other script language).
