### ISSUE TITLE
Detection area 

### ISSUE THREAD

**Issue by amounTr** [imagej/imagej#174]
Hello,
I would like to apply a region detection on pictures of greenery tiles. I tried with a plugin growing region method and also the thresholding but the obtained results were bad. Please could you give me some other solutions allowing me to detect these areas of greenness.

This is an example picture:

![img-320](https://user-images.githubusercontent.com/30657224/28957006-33db79fc-78f0-11e7-9abc-202f18dc36b8.jpg)

Thank you.

**Comment by stelfrich** [comment]
Dear @amounTr,
please re-post your question to the [ImageJ Forum](http://forum.imagej.net) since it is not development related.
Best,
Stefan

**Comment by amounTr** [comment]
Thank you for your help.

Best,

Imen

________________________________
De : Stefan Helfrich <notifications@github.com>
Envoyé : vendredi 4 août 2017 09:19
À : imagej/imagej
Cc : amounTr; Mention
Objet : Re: [imagej/imagej] Detection area (#174)


Dear @amounTr<https://github.com/amountr>,
please re-post your question to the ImageJ Forum<http://forum.imagej.net> since it is not development related.
Best,
Stefan
