### ISSUE TITLE
How to avoid: More than one item must be selected, or none

### ISSUE THREAD

**Issue by 4F2E4A2E** [imagej/imagej#176]
First of all, thank you for this amazing tool and plattform, it has been very interesting to work with this software. But when it comes to segmentation we are having a hard time labeling / annotating just one single class / selection in one image. This is the error we are always getting:

![image](https://user-images.githubusercontent.com/64590/30661027-087df8de-9e43-11e7-9bd1-4b4aba32ba45.png)

Is there any way to avoid this via a macro or plugin? I am using the [Alp’s IMage Segmentation Tool (AIMS)](https://alpslabel.wordpress.com/2017/03/28/alps-image-segmentation-tool-aims/), see macro attached: [aims.ijm.txt](https://github.com/imagej/imagej/files/1319163/aims.ijm.txt) **on line 217** and the RoiManager: https://github.com/imagej/ImageJA/blob/master/src/main/java/ij/plugin/frame/RoiManager.java#L1349

Thanks in advance!

**Comment by etarena** [comment]
Hi @4F2E4A2E - This would be a good question to post on the [ImageJ Forum](http://forum.imagej.net/) - you might get a quick(er) response there and can link it here on github.

**Comment by 4F2E4A2E** [comment]
@etarena thank you! I've just created the post: http://forum.imagej.net/t/how-to-avoid-more-than-one-item-must-be-selected-or-none/7064

**Comment by imagejan** [comment]
As this issue seems specific to your usage of the Alp’s IMage Segmentation Tool (AIMS), and it is being discussed on the forum now, I'm closing this issue.

**Comment by 4F2E4A2E** [comment]
I've find out how to do it, i just removed the if check [1] and it worked. This way we can do segmentation on images containing only one annotation.

Thank you all!
