### ISSUE TITLE
Retire jenkins.imagej.net

### ISSUE THREAD

**Issue by ctrueden** [imagej/imagej#178]
Our faithful Jenkins server has served us well for several years. However, Jenkins is a complex piece of software with many security concerns and nuances. [LOCI](https://imagej.net/LOCI) is making a concerted effort to reduce the number and complexity of services it runs, in favor of community- and cloud-based services whenever possible. E.g., rather than hosting the ImageJ source code in SCM on the LOCI server rack, all code is hosted here on GitHub. This is superior in pretty much every way, especially for community-oriented collaboration and development.

For continuous integration, the cloud-based services [Travis CI](https://imagej.net/Travis) (for Linux and macOS) and [AppVeyor](https://ci.appveyor.com) (for Windows) are freely available for OSS projects, and have become very popular and reliable. As such, the time of the ImageJ Jenkins draws to a close. This issue describes the work that needs to be done to fully migrate away from Jenkins in favor of Travis and Appyveyor for all ImageJ-related CI tasks.

* [x] __Migrate pure-Java component builds to Travis.__ Most of our components are pure Java and build the same on every platform. So we can use Travis to build `master` whenever there is a push, and deploy the result to the ImageJ Maven repository. _This replaces many individual Jenkins build jobs._
* [x] __Use Travis to release components to ImageJ Maven repository.__ This partially replaces the private `Release-Version` Jenkins job.
* [x] __Use Travis to release components to OSS Sonatype.__ This partially replaces the private `Release-Version` Jenkins job. Verify that cache invalidation still works, and/or is no longer necessary, such that released artifacts are _immediately_ available from `imagej.public` group.
* [x] __Use Travis to manage ImageJ1 repositories.__ There are [several Jenkins jobs in a chain](http://jenkins.imagej.net/view/ImageJ1/) for detecting when ImageJ1 has changed and pushing those changes to ImageJA.
* [x] __Multi-platform builds.__ We need to use both Travis and AppVeyor, and they need to detect when to auto-close (and when not to auto-close) the staging repository, such that all platform artifacts are successfully deployed.
* [x] __GPG signing.__ We want to sign all artifacts when GPG credentials are available. Right now, Jenkins only signs things being deployed to OSS Sonatype. The username is `scijava-ci` with "real" name `SciJava CI` where applicable. Email can be `scijava-ci@scijava.org` or similar. The `release-version.sh` script is currently where GPG settings are validated, but `release:perform` on the cloud side is where it will actually be used. This must be reconciled.
* [x] __Fiji distribution bundles.__ This includes [Stable-Fiji-Java-8](http://jenkins.imagej.net/job/Stable-Fiji-Java-8/) and [Stable-Fiji-MacOSX](http://jenkins.imagej.net/job/Stable-Fiji-MacOSX/).
* [x] __Convert remaining jobs to cloud CI.__ This includes:
    * [x] [SciJava Maven plugin](http://jenkins.imagej.net/job/SciJava-Maven-plugin/) – the catch with this one is that it currently deploys SNAPSHOT builds to OSS Sonatype snapshots repository – we need to decide whether to keep doing that (and if so, whether to generalize that to all OSS-Sonatype-based projects)
    * [x] [BoneJ2](http://jenkins.imagej.net/job/BoneJ2/) (bonej-org/BoneJ2#65)
    * [x] [MorphoLibJ](http://jenkins.imagej.net/job/MorphoLibJ/)
    * [x] [BAR](http://jenkins.imagej.net/job/BAR/)
    * [x] [H5J_Loader_Plugin](http://jenkins.imagej.net/job/H5J_Loader_Plugin/)
    * [ ] [github-backup-osx](http://jenkins.imagej.net/job/github-backup-osx/)
    * [x] [MPI-CBG jobs](http://jenkins.imagej.net/view/MPI-CBG/) – my preference is to simply retire these jobs; when @fjug and co. need CI builds for Indago et. al they can switch to Travis at that time 
    * [ ] [Git mirror jobs](http://jenkins.imagej.net/view/Mirrors/) – my preference, after much consideration, is to completely retire all of `git.imagej.net` – there are only a small handful of projects where I think the Git mirror is even useful, and really, we can resurrect them individually using GitHub + Travis if the need arises in the future
    * [ ] [OpenSPIM jobs](http://jenkins.imagej.net/view/OpenSPIM/)
    * [ ] [SLIM-Curve jobs](http://jenkins.imagej.net/view/SLIM-Curve/)
    * [x] [Internal server jobs](http://jenkins.imagej.net/view/Servers/) (some private jobs) – main things are: A) Drupal cron (which can be set up inside each Docker container using cron as normal); B) disk usage checks (which can be set up via cron); C) some public service validation such as the [Validate-Javadoc](http://jenkins.imagej.net/job/Validate-javadoc/) (which needs a Travis analogue somehow)
* [x] __Auto-update status.scijava.org using Travis.__ Replace obsolete [Source-Code-Status](http://jenkins.imagej.net/job/Source-Code-Status) job with (nightly?) Travis CI build of [scijava/status.scijava.org](https://github.com/scijava/status.scijava.org).

**Comment by hadim** [comment]
I don't know if it fits here but would that make sense to have a Maven plugin that can push packages to IJ Update Sites?

If you point me to the right direction, I can try to have a look.

**Comment by stelfrich** [comment]
Just noting one related point here, so we don't forget about it: can we use Travis CI to trigger the generation of the `ComponentStats` template for each plugin on http://imagej.net?

**Comment by imagejan** [comment]
@stelfrich wrote:
> can we use Travis CI to trigger the generation of the `ComponentStats` template for each plugin on http://imagej.net?

According to https://github.com/fiji/fiji/issues/121#issuecomment-306083188, it is [`mediawiki-maven-info`](https://github.com/scijava/mediawiki-maven-info) that can achieve this.

**Comment by ctrueden** [comment]
Indeed, we can have a nightly Travis cron attached to `mediawiki-maven-info` that regenerates whenever something has changed. I finally hooked up a nightly to `status.scijava.org` and it is working OK; doing it for the sidebars too would be great. But I want to take care to only push changes when things have actually changed. Needs more work than I have time to do right now. In any case, it is not a blocker for retiring Jenkins, since Jenkins currently does _not_ do this auto-status-bar-updating anyway.

**Comment by ctrueden** [comment]
An update on this: the ImageJ Jenkins was hacked a couple of weeks ago, so I forcibly retired it. But this issue remains open until all of the remaining points above are addressed.

**Comment by ctrueden** [comment]
There are no remaining jobs from Jenkins that we have missed over the past year. We are fully Travisified! 🎉

**Comment by imagejan** [comment]
> Use Travis to manage ImageJ1 repositories. There are several Jenkins jobs in a chain for detecting when ImageJ1 has changed and pushing those changes to ImageJA.

@ctrueden I noticed that the [`wayne` branch](https://github.com/imagej/ImageJA/commits/wayne) on `ImageJA` hasn't been updated since April last year. It used to mirror the commits from `imagej1` directly.

Is this something we still want/need to have? Otherwise, we should maybe delete the branch to avoid confusion.

**Comment by ctrueden** [comment]
Thanks @imagejan. I'm not 100% certain, but I don't _think_ any tooling makes use of the `wayne` branch now. So I deleted it, and we'll see if anything breaks.

**Comment by imagejan** [comment]
@ctrueden wrote:
> I don't think any tooling makes use of the `wayne` branch now. So I deleted it, and we'll see if anything breaks.

There's one situation where it would be useful to have the latest changes from `imagej1` on an own branch in `ImageJA` as well: when testing ij1-related repositories, to simplify pinning to the daily build, e.g. in https://github.com/imagej/ij1-patcher/pull/47.

See also https://github.com/imagej/ij1-builds/issues/1.
