### ISSUE TITLE
Capture Overlay in TrackMate is offset

### ISSUE THREAD

**Issue by ajnarivera** [imagej/imagej#181]
I've tried Capture Overlay several times, including after restarting my computer.  Each time it produces an offset clip:
![capture](https://user-images.githubusercontent.com/34078672/33350366-379d2e00-d453-11e7-8c4b-22720e0176a4.GIF)

**Comment by etarena** [comment]
@ajnarivera ... I reposted this issue on the fiji/trackmate repository here: https://github.com/fiji/TrackMate/issues/114

I'm closing this issue - follow at the new location.
