### ISSUE TITLE
Inconsistent point coordinates from 'Polygon' vs. 'Segmented Line' tool (among others)

### ISSUE THREAD

**Issue by imagingbook** [imagej/ImageJ#182]
While both tools create ROIs of type `ij.gui.PolygonRoi`, the point coordinates returned by `getFloatPolygon()` are **different** by 0.5 pixels in x/y. This makes it difficult do render `PolygonRoi` instances consistently.

In the attached examples, I drew various ROIs on a 10x10 noise image, then rendered the `float` coordinates of the resulting vertices (red circles). Original TIFFs (with selections) are found in the attached ZIP file. Is the obvious inconsistency between Polygon/Segmented intended? 

**Example 1: Polygon tool**
![img-PolygonM](https://user-images.githubusercontent.com/3172121/198958319-c68d2da4-a1c2-4fc5-91c6-4ab9631cb8da.png)

**Example 2: Segmented Line tool**
![img-SegmentLineM](https://user-images.githubusercontent.com/3172121/198958503-bf50efe0-507a-4f5d-a5b1-5f80d2073d28.png)

Looking at **other ROI types** shows the following situation (see [roi-test.zip](https://github.com/imagej/ImageJ/files/9899148/roi-test.zip)):
- **Line, FreehandLine, SegmentLine, Point, MultiPoint**: no offset
- **Elliptic, Oval, Polygon, Rectangle, RotRectangle**: 0.5 pix offset

Running IJ 1.53u on Win7, Java 12.0.2 (64-bit)

**Comment by rasband** [comment]
These inconsistencies are intentional. They date from ImageJ 1.52u, released in March of 2020.

Here are the relevant release notes:

* ROI enhancements, thanks to Michael Schmid:
1. Line and point selections have integer coordinates at pixel centers when displayed at high magnification. Area selections have integer coordinates at the top-left corner of pixels.
2. All interactively created ROIs, except rectangles and ovals, are created with subpixel resolution when the magnification is above 150%.
3. Removed the "Sub-pixel resolution" option from the Edit>Options>Plots dialog.
.
.

**Comment by imagingbook** [comment]
Understood, and all this has a long history, but the implementation makes it really hard to determine the "actual" ROI coordinates if needed. Ideally, the differentiation between "area" and "line" ROI (i.e., how coordinates should be interpreted) should be reflected in the class hierarchy of `Roi`, but this is clearly not the case. For example, a `PolygonRoi` may be either an "area" ROI or a "line" ROI, depending on the value of its `type` field! Similarly, a "rectangle" does not even have its own class but is an instance of `Roi` with type `RECTANGLE`. Just to illustrate, this is what I currently need to do to find out if a ROI should be rendered with a 0.5 pixel offset or not:
```
public static boolean isAreaRoi(Roi roi) {
  int type = roi.getType();
  if (roi instanceof EllipseRoi) return true;
  if (roi instanceof OvalRoi) return true;
  if (roi instanceof PolygonRoi && type == Roi.POLYGON) return true;
  if (roi instanceof Roi && type == Roi.RECTANGLE) return true;
  if (roi instanceof RotatedRectRoi) return true;
  return false;
}
```
This is certainly NOT elegant but I can live with it as long as things remain stable. However, given the circumstances, a better solution would be to add a `boolean isAreaRoi()` method to each ROI class. A pull request follows ...

**Comment by rasband** [comment]
The ImageJ 1.53v15 daily build makes the Roi.isLineOrPoint() method public and adds a Roi.translate() method.

Here is a JavaScript example:

```
  img = IJ.createImage("Untitled", "8-bit noise", 10, 10, 1);
  img.show();
  Zoom.set(img, 32);
  xpoints = [1,8.4,3.5];
  ypoints = [1,3.6,7.7];
  overlay = new Overlay();
  polygon = new PolygonRoi(xpoints,ypoints,Roi.POLYGON);
  overlay.add(polygon);
  points = new PointRoi(xpoints,ypoints,"red extra large circle");
  if (points.isLineOrPoint())  points.translate(-0.5, -0.5);
  overlay.add(points);
  img.setOverlay(overlay);
```
![Screenshot](https://user-images.githubusercontent.com/1633637/199842943-cb2c210f-6593-4b76-a6a9-c041bd4d97d5.png)
