### ISSUE TITLE
Running two Fijis at a time no longer possible?

### ISSUE THREAD

**Issue by haesleinhuepf** [imagej/imagej#184]
Hey guys,

on a recent Fiji (ImageJ 2.0.0-rc-62/1.51s; Java 1.8.0_66, Windows 10 64 Bit), it appears no longer possible to run Fiji twice. While one Fiji is running, I started another instance as debug.exe. It opens no window but finally says this on the command line:

```
[DEBUG] publish(
        context = org.scijava.Context@72b43104
        consumed = false,null,null), called from non-EDT Thread:null
[DEBUG] sendArguments: Proxy[SingleInstance$ImageJInstance,RemoteObjectInvocationHandler[UnicastRef [liveRef: [endpoint:[10.1.202.11:53905](remote),objID:[2660be8a:1609921512b:-7fff, -3108339858520516686]]]]]
[DEBUG] sendArguments: return true
[INFO] Detected existing ImageJ; passing arguments along
[DEBUG] publish(
        context = org.scijava.Context@72b43104
        consumed = false,null,null), called from non-EDT Thread:null

```

Is it possible to configure somehow that executing several instances of ImageJ is allowed?

Thanks!
Robert

**Comment by ctrueden** [comment]
Does toggling the "Run single instance listener" feature in _Edit &#9654; Options &#9654; Misc..._ make any difference? If not, it is a bug.

See imagej/imagej#98 and imagej/imagej-legacy#116 for more about the history of this feature.

**Comment by haesleinhuepf** [comment]
Ah, this option helps! I didn't even know that it exists. Thanks a lot!

Solved :-)
