### ISSUE TITLE
Problem switching LUT via new search bar

### ISSUE THREAD

**Issue by nelas** [imagej/imagej#186]
Hello! I usually switch LUTs using `L` > `LUT name` > `Enter`. I noticed that switching to the `HiLo` LUT stopped working in the new [search bar](https://imagej.net/2017-12-29_-_ImageJ2_and_Fiji_updated_-_now_with_search_bar!).

Digging a bit more, it seems that executing the [legacy LutLoader](https://github.com/imagej/ImageJA/blob/8d0f6f96c7947b8a60116dd755964d793289ec9b/src/main/java/ij/plugin/LutLoader.java) command in the new search bar applies the LUT correctly (example with `Grays`):

![screenshot from 2018-01-10 18-44-16](https://user-images.githubusercontent.com/361179/34787748-a8182250-f638-11e7-8c87-3c024926ce65.png)

But executing the [ApplyLookupTable](https://github.com/imagej/imagej-plugins-commands/blob/imagej-plugins-commands-0.7.1/src/main/java/net/imagej/plugins/commands/misc/ApplyLookupTable.java) command does not:

![screenshot from 2018-01-10 18-44-30](https://user-images.githubusercontent.com/361179/34787770-b98ec052-f638-11e7-8ae5-97a034abe083.png)

Can you reproduce the issue by `File` > `Open Samples` > `Neuron` > `L` > `Grays`?

Cheers!

**Comment by imagejan** [comment]
Yes.

This is being tracked in https://github.com/scijava/scijava-search/issues/5, so I'm closing it here.

Thanks for the illustrative screenshots though 😃
