### ISSUE TITLE
`Replace All` in Script Editor always says "0 Replacements Made!"

### ISSUE THREAD

**Issue by avh-on1** [imagej/imagej#187]
To reproduce:
1. Select "Plugins" -> "New" -> "Macro" to open the script editor
2. Add any text to the file
3. Select "Edit" -> "Find and Replace..."
4. In the "Find Next" field, put some text that occurs `n` times in the file, where `n>=1`.
5. Add any text to the "Replace with" field
6. Click "Replace All"

What happens:
* All occurrences of the "Find Next" text are replaced with the "Replace With" text.
* A popup announces "0 Replacements Made!"

What should happen:
* All occurrences of the "Find Next" text are replaced with the "Replace With" text.
* A popup announces "`n` Replacements Made!"

ImageJ 1.51s, Java 1.8.0_66 (64-bit)

**Comment by imagejan** [comment]
Thanks for spotting this. I was able to reproduce it and fixed it in https://github.com/scijava/script-editor/pull/13. The fix will be available in Fiji once a new `script-editor` release is cut and uploaded to the update site.
