### ISSUE TITLE
"Image->Transform->Rotate..." unmappable

### ISSUE THREAD

**Issue by dodewall** [imagej/imagej#188]
The "Image->Transform->Rotate..." command cannot be mapped i.e. it cannot be linked to keyboard shortcuts through ImageJ or the base operating system. I'm running the most current version of ImageJ on Mac OS Sierra. 

Although the "Edit->Selection->Rotate..." command can be mapped (both through ImageJ's "Plugins->Shortcuts->Add Shortcut by Name...." and through the Mac OS Keyboard preferences), its identically-named counterpart in the "Image" menu cannot. 

I've successfully mapped commands within the "Image->Transform" menu using both methods; it seems that the two sharing an identical name may have something to do with it. 

If anyone has any suggestions for addressing this issue, it'd be much appreciated. Thanks!

**Comment by imagejan** [comment]
@dodewall wrote:
> Although the "Edit->Selection->Rotate..." command can be mapped (both through ImageJ's "Plugins->Shortcuts->Add Shortcut by Name...." and through the Mac OS Keyboard preferences), its identically-named counterpart in the "Image" menu cannot.

The two commands are _not_ identical, you can find out using the [Macro recorder](https://imagej.net/Introduction_into_Macro_Programming#The_recorder).

* *Edit > Selection > Rotate...* is `Rotate...`
* *Image > Transform > Rotate... * is `Rotate... ` with a trailing space character

By entering "Rotate... " with the space, I was able to successfully map the command.

The presence of apparently identical menu commands is one of the ImageJ 1.x specifics that has lead to a lot of confusion in the past. In fact, ImageJ doesn't allow duplicate names for menu entries and will warn at startup if some exist.

**Comment by dodewall** [comment]
Great - thanks!
