### ISSUE TITLE
A Trojan detected by Windows Defender in FIJI distribution

### ISSUE THREAD

**Issue by hsyon** [imagej/imagej#191]
![fiji_bug](https://user-images.githubusercontent.com/36607862/36356435-4f14d56e-14af-11e8-8312-1d19313a0141.png)

Hello,
I recently downloaded a JRE only version of FIJI from the FIJI website and installed it on a new Windows 10 computer.
I would like to report that the Windows Defender scan shows there is a trojan within the FIJI distribution.
Thank you.

**Comment by ctrueden** [comment]
This is very likely a false positive. Windows Defender's recent definitions update has triggered this detection in other JAR files as well, e.g. [in IntelliJ IDEA](https://youtrack.jetbrains.com/issue/IDEA-186808).

In the case above, the affected file is listed as `ij-1.51u.jar`. If you have Apache Maven installed (see [here](http://imagej.net/CLI)), you can build the code yourself as follows:
```
git clone https://github.com/imagej/ImageJA --tag v1.51u --depth 1
cd v1.51u
mvn package
```
And then scan the `target/ij-1.51u.jar` file and see if Windows Defender complains. I am guessing that the byte-code sequence happens to match the signature of this malware, but that the malware is not actually present—JAR files cannot be infected in the same way as Windows native executables.
