### ISSUE TITLE
array.length returns string

### ISSUE THREAD

**Issue by rharkes** [imagej/imagej#192]
If an array of strings is created the length becomes of type string as well.

`array1 = newArray("a","b","c","d");`
`array2 = newArray(1,2,3,4);`
`array3 = newArray(array1.length);`
`array4 = newArray(array2.length);`

Now we have this situation:
`Array.print(array3);`
returns `4`
`Array.print(array4);`
returns `0,0,0,0`

**Comment by imagejan** [comment]
This is an issue with [`imagej/imagej1`](https://github.com/imagej/imagej1). @rasband any insight?

**Comment by rasband** [comment]
This is an ImageJ 1.51u regression that is fixed in the 1.51v daily builds.
