### ISSUE TITLE
Strange value of constant ImageProcessor#NO_THRESHOLD

### ISSUE THREAD

**Issue by imagingbook** [imagej/ImageJ#193]
It appears that this constant in `ImageProcessor` is initialized with a rather strange value:

``public static final double NO_THRESHOLD = -808080.0;``

By default, this value is returned by both `ImageProcessor.getMinThreshold()` and `getMaxThreshold()`, which does not seem intuitive. How about using `Double.NaN` instead?

**Comment by rasband** [comment]
I agree this is not intuitive but I can't switch to using Double.NaN without breading existing plugins.

**Comment by rasband** [comment]
The ImageJ 1.54a25 daily build adds an ImageProcessor.isThreshold() method. There was already an ImagePlus.isThreshold() method.
