### ISSUE TITLE
Java 10 exceptions on macOS X

### ISSUE THREAD

**Issue by cortig** [imagej/imagej#200]
Fiji and ImageJ can properly launch with he Java 10.0.1 JDK installed, but at every launch, there is a long list of exceptions that pop-up. The exceptions seem to emanate from this issue:
java.lang.NoClassDefFoundError: com/apple/eawt/ApplicationListener

**Comment by mngad** [comment]
The f is w da 7

On 19 May 2018 21:25, Jan Eglinger <notifications@github.com> wrote:

See also #197<https://github.com/imagej/imagej/issues/197>.

**Comment by ctrueden** [comment]
Closing in favor of #197.
