### ISSUE TITLE
ImagePlus.setPositionWithoutUpdate does not work for Hyperstacks

### ISSUE THREAD

**Issue by Sethur** [imagej/ImageJ#201]
On ImageJ v1.54c7, `ImagePlus::setPositionWithoutUpdate(int channel, int slice, int frame)` does still redraw and update the window (including the scrollbars) when used on hyperstacks, because the `noUpdateMode` class variable is ignored when `isDisplayedHyperstack` is true.

As a workaround, I currently have to use hard-to-interpret code like:
```
imp.setSliceWithoutUpdate((t-1)*slices*channels + (z-1)*channels + ch);
```

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.54c14 daily build.
