### ISSUE TITLE
Thresholding broken in ij52b.jar

### ISSUE THREAD

**Issue by cortig** [imagej/imagej#202]
If I open an image in ij52b.jar and use Adjust > Threshold, I get the thresholding pane.
I can make all the adjustments I want on the sliders, but when I hit Apply, the thresholding changes to a completely different value (with a minimum value much lower than what I had selected).
The value seems to be always the same, regardless of what adjustments I had made with the sliders.

That seems to be new to this build. I never experienced it before.
I was able to revert to ij1.51w which did not exhibit this issue: the applied threshold corresponds to what was selected in the thresholding sliders and previewed on the image.

**Comment by rasband** [comment]
This regression is fixed in the latest ImageJ daily build (1.52c14).

**Comment by imagejan** [comment]
See also [this forum discussion](http://forum.imagej.net/t/bug-using-apply-threshold-for-16bit-images/10825?u=imagejan) that might be related.
