### ISSUE TITLE
error for each slice in stack when saving as Animated Gif

### ISSUE THREAD

**Issue by ahillsley** [imagej/ImageJ#204]
When saving an image stack as an animated gif I get an error "java.lang.illegalArgumentException: Image must be 8-bit". This error then appears for each slice in the stack. Meaning that for a stack of 300 images I get 300 errors that each appear in sequence only after the previous error is closed.

**Comment by rasband** [comment]
I am not able to reproduce this bug using ImageJ's built in File>Save As>Gif command or with Fiji's File>Save As>Animated Gif plugin.

**Comment by bogovicj** [comment]
I can reproduce the problem with:
* `File > Open Samples > T1 Head (16 bits)`
* `File > Save As > Animated Gif...` (with default options)

(ImageJ 1.53t)

**Comment by ctrueden** [comment]
Thanks @ahillsley for the report and @bogovicj for the recipe to reproduce. I fixed it and released IO_ 4.2.1. Will be part of Fiji 2.10.0.
