### ISSUE TITLE
imagej-launcher-5.0.0-amd64-Linux-gcc-executable missing (rc-66 regression)

### ISSUE THREAD

**Issue by slokhorst** [imagej/imagej#204]
If I run `mvn -Papp` with the imagej-2.0.0-rc-66 release, it fails with the following error:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.0.0:unpack (unpack) on project imagej: Unable to find/resolve artifact.: Could not find artifact net.imagej:imagej-launcher:nar:amd64-Linux-gcc-executable:5.0.0 in imagej.public (http://maven.imagej.net/content/groups/public) -> [Help 1]`

[Full log](https://github.com/imagej/imagej/files/2054786/mvn.log)

If I run the same command with the imagej-2.0.0-rc-**65** release, the app is succesfully built. (it seems to download version 4.0.5 of imagej-launcher instead of 5.0.0)

Using OpenJDK8 on Arch Linux.

**Comment by slokhorst** [comment]
Still happens with the imagej-2.0.0-rc-67 and imagej-2.0.0-rc-68 releases.

**Comment by slokhorst** [comment]
Managed to fix it with [these changes](https://github.com/slokhorst/imagej/commit/93e9e768a0898e58649d1f4c1385432d38676da2) and
```bash
mvn -Papp -Dimagej-launcher.version=5.0.1-SNAPSHOT
```

**Comment by ctrueden** [comment]
Thanks for the update, @slokhorst. I will try to find time to address this.

**Comment by ctrueden** [comment]
@slokhorst I finally merged @stelfrich's PR. Did not test, though. Please try it on the newest master branch, and reopen this issue if it's still a problem.
