### ISSUE TITLE
Selection from ROI manager onto a new image

### ISSUE THREAD

**Issue by erinmerchant** [imagej/imagej#207]
Hi everyone,

I am relatively new to ImageJ macro writing, but I have come across this issue. I am looking at images of the mouse brain and trying to analyze the particles in that image. However, there are pieces of the next slice of brain in the image where those particles are also being counted; I essentially want to remove the edges and only take the centermost part of the image. So far, I have done the following: 
    open(file); //file is defined earlier in the script
    run("8-bit");
    run("Gaussian Blur...", "sigma=60");
    setAutoThreshold("Default");
    run("Threshold...");
    setThreshold(0, 240);
    run("Convert to Mask");
    run("Analyze Particles...", "display exclude summarize add"); 
Doing this gives a selection around the part of the image I care about. Now what I am trying to do is take this/these selections (as it only excluded them on the edges, and there are small pieces around the brain), and put it back on the original image and essentially crop the unnecessary parts out. The way I have been doing it was the following: 
   roiManager("Select", 0);
   run("Clear Outside");
However, this didn't work because the selection that I care about isn't always index 0, and the selection can change based on the image. I would like to batch process this cropping aspect but am not sure if I can write a macro that takes a range of selections that doesn't include the edges, such as 
      i=roiManager("count");
      roiManager("Select", 0 to i)); //taking the range of indexes from 0 to i
or
    roiManager("Select", 0);
    setKeyDown("shift");
    roiManager("Select", i);
These do not work, but I thought they would be useful in explaining what I am trying to do. I tried making an array, but I am not really sure how. If there was a macro part that is the equivalent of ROI Manager--> More-->AND, this will do, but it doesn't show up on the Recorder macro. Or, if I can put a size filter on an ROI and then have it select the largest and/or centermost selection, this will work, but I am unsure how to do this. Any help with this would be greatly appreciated!!

**Comment by imagejan** [comment]
Please have a look at the macro functions documentation, in particular:
https://imagej.net/developer/macro/functions.html#roiManager(%22and%22)

and post more specific follow-up questions on the [ImageJ forum](http://forum.imagej.net/).
