### ISSUE TITLE
Support for float32 RG, RGB and RGBA images

### ISSUE THREAD

**Issue by rggjan** [imagej/imagej#208]
Currently, raw float32 grayscale images can be opened in imagej as "32-bit Real". However, there is no option to load float images with multiple channels. This would be a great addition.

**Comment by imagejan** [comment]
There is, take e.g. this macro:

```
newImage("HyperStack", "32-bit composite-mode label", 100, 100, 3, 1, 1);
```

which will open a 3-channel, 32-bit per channel image.

Do you have a specific *file format* in mind which you try to open?

**Comment by imagejan** [comment]
> Is this available in the ImageJ GUI?

*File > New > Hyperstack...*

If you have usage questions, I warmly recommend asking on https://forum.image.sc

**Comment by rggjan** [comment]
Thanks @imagejan 

However, I don't want to create a new Hyperstack, I want to open an existing image file on disk. Which I think is impossible. Which is why I filed an enhancement request here...

Or did I miss anything?

**Comment by imagejan** [comment]
Ah, ok. That's why I was asking about the file format. Can you provide an example file? Maybe *File > Import > Raw...* helps here?

In any case, this is not about lacking support for the 32-bit-per-channel type. It's about how to get your data into ImageJ in the right format, and thus belong more likely to either `imagej1` or `bio-formats`, `scifio`, `imglib2`. I think it would still be better to discuss this on the forum, so this is more visible to others in the community who might be(come) interested.

**Comment by rggjan** [comment]
Import > Raw only supports "32-bit Real" which is a single channel float image, as mentioned (probably not that clearly ;) in the first comment by me. It doesn't support rg, rgb or rgba images.

But sure, I'll file a bug report somewhere else. Maybe you can give me a pointer as to what of the many repositories is responsible for the UI dialog of "File -> Import -> Raw"?

**Comment by imagejan** [comment]
https://github.com/imagej/ImageJA/blob/c112f7195005814c14092b98bac1aab2c334e95c/src/main/java/ij/plugin/Raw.java

I got this using the [search bar](https://imagej.net/2017-12-29_-_ImageJ2_and_Fiji_updated_-_now_with_search_bar!), typing "Raw..." and then pressing the *Source* button.

For the `ImageJA` repository, it's important to know that it is automatically synced from the [`imagej1`](https://github.com/imagej/imagej1/) repository, and that for ImageJ1 functionality, it's usually best to contact Wayne @rasband directly, he's the maintainer of ImageJ1.

**Comment by rggjan** [comment]
Awesome, thanks a lot @imagejan for your help! I contacted Wayne directly, closing this request then...
