### ISSUE TITLE
Cannot export uncompressed avi file using save as > avi (compression: None)

### ISSUE THREAD

**Issue by shalinshah1993** [imagej/imagej#210]
When I try to export an import `lif` file as an uncompressed `avi` video file, imagej automatically downgrades the 16-bit video to 8-bit. Any workarounds or known solutions? In particular, I think this is the plugin responsible for error - https://imagej.nih.gov/ij/plugins/avi.html

**Comment by imagejan** [comment]
This issue belongs into [`imagej1`](https://github.com/imagej/imagej1), the `AVI_Writer` plugin source is here:

https://github.com/imagej/imagej1/blob/master/ij/plugin/filter/AVI_Writer.java#L183

In that linked line, there's also a comment mentioning that all grayscale image types are always written as 8-bit.
You could try using *Plugins > Bio-Formats > Bio-Formats Exporter* instead.

**Comment by shalinshah1993** [comment]
Thanks for the prompt response. I tried _Plugins > Bio-Formats > Export As > AVI file_. The error I get is uint16 is not supported by this type of format.

**Comment by ctrueden** [comment]
I didn't think the AVI file format supported 16-bit integer data. Does it?

**Comment by shalinshah1993** [comment]
Yeah, I just did some research. It seems that AVI encoding doesn't support 16-bit. It is not a imagej or plugin bug. Thanks for the help!
