### ISSUE TITLE
Starting ImageJ from a java program leaves ImagePlus detached.

### ISSUE THREAD

**Issue by odinsbane** [imagej/imagej#212]
I have some programs that I run, and they start imagej while running.  For example.

    ImageJ.main(new String[] {});
    Path path = Paths.get(IJ.getFilePath("select segmentation to label"));
    ImagePlus plus = new ImagePlus(path.toAbsolutePath().toString());
    plus.show();

If I run this once, everything works as expected. If I run this again while the first imagej window is still visible, the the second ImagePlus will open without an ImageJ window. I don't mind the lack of a second window, but I cannot access the second ImagePlus, eg save the file, process or adjust contrast.

I think this is a new behavior, but I am not sure. I am using ImageJ 1.51r

**Comment by imagejan** [comment]
It seems you're using [`ij.ImageJ`](http://javadoc.scijava.org/ImageJ1/ij/ImageJ.html) (not [`net.imagej.ImageJ`](http://javadoc.scijava.org/ImageJ/index.html?net/imagej/ImageJ.html)) in your code snippet, so this issue rather belongs to [`imagej1`](https://github.com/imagej/imagej1/issues).

Why do you need to call `ImageJ.main` at all?

**Comment by odinsbane** [comment]
True, this should probably be an imagej1 issue. 

I don't always like to start my programs from imagej, especially when I am developing them. But I like to have imagej running so I can do things like save and adjust contrast. Which I cannot do with just an ImagePlus window.

**Comment by imagejan** [comment]
I recommend using a `main` method in your plugin then, modeled after the one in [`imagej/example-legacy-plugin`](https://github.com/imagej/example-legacy-plugin):

https://github.com/imagej/example-legacy-plugin/blob/6d0eb4b7e3a289acc580a0da72e21821c624ef14/src/main/java/com/mycompany/imagej/Process_Pixels.java#L163-L187

**Comment by ctrueden** [comment]
@odinsbane From the exchange above, I take it you solved your issue? Therefore I'm closing this issue. If I am incorrect and there is still a problem, please feel free to reopen with details.
