### ISSUE TITLE
Incorrect displaying multi-page TIFF with tags 50838 & 50839 in each IFD

### ISSUE THREAD

**Issue by okdzhimiev** [imagej/imagej#213]
I have a python script (using Pillow) generating a multi-page TIFF. Pillow duplicates IFDs for each page so - 50838 and 50839 present in each IFD. When opening with ImageJ this results in a page 'shifting' like in [multipage_test.tiff](https://community.elphel.com/files/ijtiff/multipage_test.tiff).

When generating multipage TIFF using ImageJ code - it puts 50838 and 50839 only in the first IFD.

Is it a bug or is it supposed to work like this?

Thanks

**Comment by imagejan** [comment]
The file loads correctly (i.e. without shift) when opening it with **SCIFIO** (via *File > Import > Image...* or when SCIFIO is activated in *Edit > Options > ImageJ2...*) or with **Bio-Formats** (using *Plugins > Bio-Formats > Bio-Formats Importer*), so this is most likely a bug in [`imagej1`](https://github.com/imagej/imagej1).

@rasband any comments?

**Comment by okdzhimiev** [comment]
Thanks the quick response.

I have tried the way you described - the image is displayed correctly but it does not decode&display stack labels recorded in 50839. Like if opened with:
- ImageJ1 (1.52e) - it reads: "1/5 (diagm-pair);"
- ImageJ2 (2.0.0-rc-68?) - "1/5 (1);"

Note 1: if put something meaningless in 50839 - the file loads correctly even with IJ1 1.52e.
Note 2: ImageJ2 does not decode labels for 'correctly' created TIFF. Try [1521849031_093189-ML_DATA-08B-O-OFFS1.0.tiff](https://community.elphel.com/files/ijtiff/1521849031_093189-ML_DATA-08B-O-OFFS1.0.tiff). It's probably not implemented.

**Comment by rasband** [comment]
The file claims to be created by ImageJ (the image description starts with "ImageJ=") but it is not in the format of a TIFF stack created by ImageJ. The IFDs are between the images instead of at the end of the file. The ImageJ TIFF reader assumes the images are contiguous in TIFF stacks created by ImageJ.  I could fix this problem if there was a way to determine that the file was not created by ImageJ.

**Comment by okdzhimiev** [comment]
IFD[0] is in the beginning of the file, and IFD[1:] are stacked in the end of the file and never read, correct? If yes, then I'll try to modify my python script.

**Comment by rasband** [comment]
"IFD[0] is in the beginning of the file, and IFD[1:] are stacked in the end of the file and never read, correct?"

That is correct.

**Comment by okdzhimiev** [comment]
Alright, I was able to generate a correct tiff stack using **tifffile.py**.
Thanks for the help.
