### ISSUE TITLE
Table.set() will result in a blank table opened after a macro is run

### ISSUE THREAD

**Issue by Phiir42** [imagej/ImageJ#215]
If the built-in Table.set(columnName, rowIndex, value) is used on a table within a macro, and that table is subsequently closed, a blank table with the same name will reopen after the macro is finished running.

Simplest reconstruction:
macro "Test" {
	Table.create("Table");
	Table.set("a", 0, 1);
	close("Table");
}

**Comment by rasband** [comment]
This bug is fixed in the ImageJ 1.54g1 daily build.
