### ISSUE TITLE
Adiposoft not recording manual entries to Excel

### ISSUE THREAD

**Issue by racox** [imagej/imagej#216]
Hello,
I have used the Adiposoft plugin before without issue but this time, when I manually add, delete, separate cells and then select end to save the file, the saved Excel file only shows the measurements from the automated detection and not the manual changes made after. I would appreciate any help since I lost a week's worth of work and for some reason the software no longer identifies half the cells in the image requiring significant manual work.
Thanks,
Aaron

**Comment by ctrueden** [comment]
Thanks for the report, @racox, and sorry to hear that you lost work. This issue tracker is for core ImageJ issues, as opposed to plugins. Since your issue issue is with the Adiposoft plugin, please post on the [Image.sc Forum](https://forum.image.sc/), tagged with `imagej` and `adiposoft`. There is a friendly community there that will try to help you!

**Comment by racox** [comment]
Ok, thank you Curtis. I posted on the other site.

Best,
Aaron

On Oct 19, 2018, at 2:06 PM, Curtis Rueden <notifications@github.com<mailto:notifications@github.com>> wrote:

***CAUTION:*** This email is not from a BCM Source. Only click links or open attachments you know are safe.
________________________________

Thanks for the report, @racox<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_racox&d=DwMFaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=z4CdEhWSkD9p-6w7PYWP-g&m=6nCPVlqfYzWDJFrOKHEYJhWU6QXyWAi9LJAJ7HB4wLI&s=9jNOdTr5VTjrVPUFcyY1tDG069-wKqlfwQgjWl2SPmg&e=>, and sorry to hear that you lost work. This issue tracker is for core ImageJ issues, as opposed to plugins. Since your issue issue is with the Adiposoft plugin, please post on the Image.sc Forum<https://urldefense.proofpoint.com/v2/url?u=https-3A__forum.image.sc_&d=DwMFaQ&c=ZQs-KZ8oxEw0p81sqgiaRA&r=z4CdEhWSkD9p-6w7PYWP-g&m=6nCPVlqfYzWDJFrOKHEYJhWU6QXyWAi9LJAJ7HB4wLI&s=Z0sL-19bvhEy30_vIsz-X5CtGKm6NL4m5JcK_CvHI30&e=>, tagged with imagej and adiposoft. There is a friendly community there that will try to help you!

**Comment by ctrueden** [comment]
Great. For those who come across this issue later, the relevant thread is [here](https://forum.image.sc/t/adiposoft-not-recording-manual-measurements-to-excel/20375).
