### ISSUE TITLE
Return values ignored

### ISSUE THREAD

**Issue by scuniff** [imagej/ImageJ#218]
https://github.com/imagej/imagej1/blob/master/ij/plugin/filter/Rotator.java

 Return value from String.replaceAll() is ignored so the replacement is not seen.

                macroOptions.replaceAll(" interpolate", " interpolation=Bilinear");

should be

               macroOptions = macroOptions.replaceAll(" interpolate", " interpolation=Bilinear");

===================================================

https://github.com/imagej/ImageJ/blob/master/ij/Menus.java

Return value from String.trim() is ignored so the trim is not seen.
              

               command.trim();

should be 

                command = command.trim();

This occurs twice

**Comment by rasband** [comment]
These bug fixes are in the ImageJ 1.54f4 daily build. The commit is at https://github.com/imagej/ImageJ/commit/f4913997eb238160031fe1bcbc309669d4384ce1.
