### ISSUE TITLE
How to use 3Dviewer in Java8 on MacOSX?

### ISSUE THREAD

**Issue by yaya1026** [imagej/imagej#225]
Hi, I always use this wonderful tool.

I try to use 3dviewer in my program.
When i build this program, i get this error message.
```
java.lang.NoClassDefFoundError: javax/media/opengl/GLException
```
or
```
java.lang.NoClassDefFoundError: javax/media/opengl/glcapabilitieschooser
```
However, the same program can be build in Java6 and MacOSX Yosemite or Java8 and Windows7.

My environment
OS: MacOS Mojave
Java version: 8
ImageJ version: 1.51n

I've already included j3dcore, j3dutils and vecmath.jar.
How to use 3Dviewer in Java8 on MacOSX?

**Comment by ctrueden** [comment]
Sorry for the delay in reply, @yaya1026. The short version is: you need a newer version of the Java-3D artifacts, rewritten to be built on top of JOGL.

Please give the latest version of [Fiji](https://fiji.sc/#download) a try. I did a lot of work to make the 3D Viewer plugin work with Java 8 on macOS. There are some outstanding issues (https://github.com/fiji/3D_Viewer/issues/15, https://github.com/fiji/3D_Viewer/issues/18), but for most people it seems to be working well enough.

See also:
* https://imagej.net/Java_3D
* https://imagej.net/Java_8#About_Java_3D

Happy to discuss further on https://forum.image.sc if you get stuck or have additional questions!
