### ISSUE TITLE
Add naming textbox to (raw) import dialog

### ISSUE THREAD

**Issue by eyalroz** [imagej/ImageJ#227]
I occasionally use ImageJ to examine sets of 2D images, which I access using File > Import > Raw... ; when I choose the first file, I get an import dialog with all sorts of options. However - I don't get a text box for me to choose a name for the loaded image, and have to then right-click the resulting window's content area and choose "Rename" in the context menu.

It would be nice if the import dialog asked me for a new for the image sequence (e.g. via a textbox with the default value ImageJ is thinking of assigning).

**Comment by rasband** [comment]
Upgrade to the latest ImageJ daily build (1.54g26) and the File>Import>Raw command will use the directory name as the image title when the "Open all files in folder" option is enabled.

**Comment by eyalroz** [comment]
@rasband : That would be an improvement; although I would still add the textbox, with the directory name as the initial value. This would make sense when:

* The interesting path element is not the last one, but an earlier one (e.g.`/path/to/my_interesting_name/raw_slices/`)
* The desired name is made up multiple path elements
* The person opening the files did not consider carefully naming folders beforehand
