### ISSUE TITLE
Results Table label disappeared for ROI line measurement

### ISSUE THREAD

**Issue by cyrilturies** [imagej/imagej#228]
Hello,

I noticed when measuring ROI of lines (straight, segmented, freehand or arrows), name of ROI is not reported in the Results Table.
It is thus impossible to check or select a result line by its name with this empty Label.

This is not the same for other selection types, rectangle, oval, etc. are correctly labelled in the Results Table.

![roi-results](https://user-images.githubusercontent.com/25366152/51965863-155c9380-246b-11e9-8d22-200977fb6080.jpg)

If someone can help fixing this issue.

My version of ImageJ is 1.52i (win64) on Windows 7

**Comment by imagejan** [comment]
Interesting observation. This only seems to happen if none of the measurement options in *Analyze > Set Measurements...* (except *Display label*, of course) is selected.

**Comment by cyrilturies** [comment]
Thanks for your help Jan!

I've just added the "area" in Set Measurements and the Label row came back for measured ROI.

`run("Set Measurements...", "area display redirect=None decimal=3");
roiManager("UseNames", "true");`

**Comment by rasband** [comment]
The bug is fixed in the latest ImageJ daily build (1.52m1). Code changes are at
https://github.com/imagej/imagej1/commit/25feaa194a895a4865aea83ef283dd7293fbe455
