### ISSUE TITLE
Letter size too small on high-DPI screen

### ISSUE THREAD

**Issue by Silver-Fang** [imagej/imagej#230]
My Surface Book has a 3000×2000 screen and this app's window is only 5.4㎝×1.4㎝ shown. I got sore eyes after working for minutes.

**Comment by ctrueden** [comment]
Please take a look at these hints:

https://imagej.net/Windows#HiDPI_displays

You can also try [installing Java 11](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot) and [launch ImageJ with that version of Java](https://imagej.net/FAQ#How_do_I_launch_ImageJ_with_a_different_version_of_Java.3F), and see whether that makes a difference.

**Comment by carloserodriguez2000** [comment]
Change the screw resolution or hook up an external monitor.

**Comment by ctrueden** [comment]
Closing this issue, but please feel free to reopen with more details if none of the suggestions above work for you!
