### ISSUE TITLE
using imagej to track frame by frame video formatted in .ts

### ISSUE THREAD

**Issue by rambunctiouslad** [imagej/imagej#233]
basically, I want to be able to go through a video fram by frame, tracking progress from one to the next. only problem is that the video I have is formatted as .ts, which imagej or fiji don't recognize. another issue is that the video is largr than 4gb, and therefore most converters I've seen cant deal with that size. any suggestions?

**Comment by imagejan** [comment]
@rambunctiouslad would you mind posting your question on the [image.sc forum](https://forum.image.sc)? This issue tracker is rather for issues with the ImageJ source code, not for general usage questions.

**Comment by rambunctiouslad** [comment]
@imagejan oh yeah,totally my bad

**Comment by ctrueden** [comment]
Thanks @rambunctiouslad. For the record, question was posted here:
https://forum.image.sc/t/using-imagej-fiji-to-track-a-video-frame-by-frame-in-ts-format/23975
