### ISSUE TITLE
When importing an image sequence as a virtual stack only one frame of each image is included.

### ISSUE THREAD

**Issue by odinsbane** [imagej/ImageJ#242]
Some tif files have an issue where importing them and checking the virtual stack box causes an incorrect number of images to be loaded. If the images are loaded as non-virtual stacks then all of the images are loaded.

This only happens for some tif files, this is one way to generate tif files that fail.

```
#!/usr/bin/env python3

import numpy, imageio

x0 = numpy.array( numpy.random.random((2, 32, 32))*255, dtype="int8")
x1 = numpy.array( numpy.random.random((2, 32, 32))*255, dtype="int8")

imageio.volwrite("test-0.tif", x0)
imageio.volwrite("test-1.tif", x1)
```

**Comment by rasband** [comment]
The fix for this bug by @odinsbane is in the ImageJ 1.54k1 daily build. The commit is at https://github.com/imagej/ImageJ/commit/8fa08fa17d0729930209bb1cf894c72f7d63e6e3.
