### ISSUE TITLE
Abandon JAVA?

### ISSUE THREAD

**Issue by jobs-git** [imagej/ImageJ#248]
Soon: https://en.wikipedia.org/wiki/Google_LLC_v._Oracle_America,_Inc.#:~:text=Oracle%20asserted%20Google%20was%20aware,Google%20therefore%20infringed%20Oracle's%20copyright.

**Comment by ATpoint** [comment]
Is this a trolling attempt?

**Comment by ctrueden** [comment]
No one is going to (or realistically be able to) sue anyone due to ImageJ being built on OpenJDK.
