### ISSUE TITLE
java.awt.HeadlessException since 1.54i

### ISSUE THREAD

**Issue by rudolphi** [imagej/ImageJ#253]
Since 1.54i, ij.io.FileOpener calls Recorder.suspendRecording(), and ij.plugin.frame.Recorder:33 defines a field
	private static TextArea textArea = new TextArea();	//recorded code goes here (start with dummy to avoid NullPointerException)
that results in java.awt.HeadlessException -> java.lang.ExceptionInInitializerError in a headless environment (JSP server).

**Comment by rasband** [comment]
This regression is fixed in the ImageJ 1.54k8 daily build. The commit is at https://github.com/imagej/ImageJ/commit/8799326e2cd8b7f23f7f8648e8cb39f11b6f0383.

**Comment by rasband** [comment]
The Recorder in the ImageJ 1.54k11 daily build no longer creates a TextArea at line 33. The commit is at [2024.07.11 (1.54k10; Recorder) · imagej/ImageJ@0abfe3e · GitHub](https://github.com/imagej/ImageJ/commit/0abfe3ef661efb7941429ac493a47c6faffb6044).
