### ISSUE TITLE
Parameters with visibility = ItemVisibility.MESSAGE block macro execution by showing a dialog

### ISSUE THREAD

**Issue by mdoube** [imagej/imagej#253]
In IJ2-style plugins it is sometimes helpful to display a message in the dialog box in interactive mode. This is usually achieved by including a Parameter like so:
```
@Parameter(visibility = ItemVisibility.MESSAGE, columns = 1, persist = false)
private String loopSection = "-- LOOPS --";
```
Unfortunately, if the plugin is called from a macro a dialog will pop up containing the contents of the `String` and an `OK` button. The macro stalls and waits for user input, making it difficult to run in batch mode. Workarounds proposed so far include users abandoning macros and going to Python, but there is not yet a Python recorder that works as well as the macro recorder; or to add a code snippet to the end of the macro call, which doesn't  always work, and requires the user to dive into Java code to find out the variable name of the `String`.

In BoneJ we have stopped using messages like this because of the inconvenience to macro script users, see e.g.:
https://github.com/bonej-org/BoneJ2/issues/267

And:
https://forum.image.sc/t/bonej-fractal-dimension-and-ij-robot-how-to-automatically-press-ok-on-dialog-box/39459

**Comment by imagejan** [comment]
Duplicate of https://github.com/scijava/scijava-common/issues/299.

You can work around the issue by adding `required = false` to the `@Parameter` annotation.

**Comment by mdoube** [comment]
> You can work around the issue by adding `required = false` to the `@Parameter` annotation.

OK, will bear that in mind for future development.

Looking at the messages in question showed that they weren't particularly helpful, and added clutter to the dialogs, so for us the sensible thing to do was remove them.

**Comment by mdoube** [comment]
Closing as duplicate of https://github.com/scijava/scijava-common/issues/299
