### ISSUE TITLE
Maven repository issues

### ISSUE THREAD

**Issue by sebastian-raubach** [imagej/imagej#255]
There seems to be issues with some of the packages hosted on your maven repository.
I'm trying to use `ch.systems.cisd:jhdf5` and it's been working fine until today or a few days ago.
When searching for it through the web interface, I can find the package, but when selecting it, I get a code 500 error:
https://maven.scijava.org/#nexus-search;quick~ch.systems

Navigating to the pom or jar themselves gives a more detailed message:
> 500 - Internal Server Error
> Exception during reading up an item from FS storage!

https://maven.scijava.org/service/local/artifact/maven/redirect?r=ome-external&g=ch.systems.cisd&a=jhdf5&v=14.12.1&e=jar

It it possible to check why this is happening? Thanks!

**Comment by sebastian-raubach** [comment]
It looks like this is resolved now.

**Comment by imagejan** [comment]
This was a temporary server issue. Thanks for confirming that it's resolved. I'm closing this ticket then.

(See also [this forum topic](https://forum.image.sc/t/maven-scijava-org-500-error-when-requesting-fiji-sc2-0-0-snapshot/41030?u=imagejan).)

**Comment by ctrueden** [comment]
Yep, the 500s have been resolved.

There still seems to be an issue with artifacts newly published to Central not being available from our Nexus public group for 2-3 days. @sebastian-raubach Please report any future issues on forum.image.sc and mention `@ctrueden`. Thanks!
