### ISSUE TITLE
Enable CORS for the sample images on imagej.net

### ISSUE THREAD

**Issue by oeway** [imagej/imagej#256]
This is a feature request about the imagej.net website, sorry if I am posting in the wrong place.

For the "Open Samples" menu in ImageJ.JS (https://ij.imjoy.io/), we cannot read images from the browser because there is no CORS header sent by the imagej.net server. I had to [use a cors proxy server](https://github.com/imjoy-team/imagej.js/blob/5f5eae8ba2e434a7b2e9027ccf914f1af65bc69b/src/index.js#L88-L90) to load sample images for the moment, but all the data will pass through a free proxy server which can be slower, insecure (e.g. when fetching macro scripts), unstable. Would be nice if imagej.net could enable the CORS header directly.

**Comment by ctrueden** [comment]
@oeway I've enabled CORS for all LOCI-managed sites. Please let us know how it works for you now.

CC @hinerm

**Comment by oeway** [comment]
It works perfectly! Thanks!

Just tried, open samples images becomes much faster as well.
