### ISSUE TITLE
Disabling "Save column headers" on I/O options does not disable column headers

### ISSUE THREAD

**Issue by nelas** [imagej/imagej#261]
Hi! It seems that changing the `Save column headers` checkbox on `Input/Output Options` has no effect. The saved text file always contains the column headers:

![Screenshot from 2020-09-17 23-33-58](https://user-images.githubusercontent.com/361179/93531254-31ae8c00-f93f-11ea-8f74-b20e17020998.png)

On `Fiji/ImageJ 2.1.0/1.53c`. Possibly related to [this commit](https://github.com/imagej/imagej1/commit/19962aa677cfef56e6a7d5919fa3e1e97f531199#diff-07dab2319d92253c674169919b15c1cd)?

Thanks!

**Comment by imagejan** [comment]
Thanks for reporting this. This functionality is in [`imagej1`](https://github.com/imagej/imagej1), so I'm tagging @rasband here.

**Comment by rasband** [comment]
This ImageJ 1.53c regression is fixed in the 1.53f17 daily build.
