### ISSUE TITLE
Feature request: add magnifying glass popup menu

### ISSUE THREAD

**Issue by oeway** [imagej/imagej#266]
Currently the magnifying glass works by right and left clicking, however, there is no right click with [ImageJ.JS](https://ij.imjoy.io) on mobile or tablet. One solution is to add an additional popup menu for selecting zoom in and zoom out explicitly.

**Comment by imagejan** [comment]
The magnifier tool implementation is in `imagej1` in `Toolbar.java`:

https://github.com/imagej/imagej1/blob/c70a30b718126f5d8cd7b3fc754aa5395c9412cd/ij/gui/Toolbar.java

@rasband will have to decide how to adapt the implementation.

**Comment by rasband** [comment]
The ImageJ 1.53f43 daily build adds a magnifying glass tool popup menu and it supports long presses to trigger popup menus.

**Comment by oeway** [comment]
Thanks @rasband !
