### ISSUE TITLE
Macro getVersion() return does NOT include daily build number

### ISSUE THREAD

**Issue by rgaiacs** [imagej/imagej#276]
When I go to `Help` > `About ImageJ...`, I get something like

![imagej](https://user-images.githubusercontent.com/1506457/104142744-d1fd5480-53f7-11eb-926f-eab88870da08.png)

The version number includes the daily build number. When I call the macro `getVersion()`, it does **not** provide the daily build number:

```
$ imagej --headless --console -eval "print(getVersion());" | tail -n 1
2.1.0/1.53h
```

What do you think about include the daily build number in the output of `getVersion()`?

**Comment by imagejan** [comment]
You can use `IJ.getFullVersion()` (in IJ1 macro language or any other supported scripting language):

    $ imagej --headless --console -eval "print(IJ.getFullVersion)" | tail -n 1

**Comment by rgaiacs** [comment]
Thanks!
