### ISSUE TITLE
Will ImageJ get rid of using Java?

### ISSUE THREAD

**Issue by amh737** [imagej/imagej#282]
With Java being paid for now, will imageJ be looking at migrating to a different scripting program? Looking so we know if we need to purchase Java or not.

Thank you!

**Comment by axtimwalde** [comment]
ImageJ runs with free version of Java http://imagej.1557.x6.nabble.com/Java-version-for-Fiji-and-ImageJ-td5022925.html

**Comment by amh737** [comment]
@axtimwalde, thank you for providing this! Is there any type of "formal documentation" on this or just what is listed here on this link? Our university campus IT is requiring proof that no subscriptions to Oracle Java is needed. Thank you!

**Comment by ctrueden** [comment]
@amh737 To whom it may concern:

The ImageJ and Fiji software applications and libraries are designed and tested for use with OpenJDK 8 and later. All features work out of the box with open source versions of the Java runtime environment, including Azul's Zulu, and JetBrains's JBRSDK. Other open-source flavors (e.g. Amazon Corretto) are likely to work fine as well. The Oracle version of Java is not required nor recommended for use with ImageJ or Fiji.

Sincerely,
Curtis Rueden
ImageJ2 & Fiji project lead
