### ISSUE TITLE
Decide how `ij.ui().show(imageDisplay);` should work when no UI is visible

### ISSUE THREAD

**Issue by apal4** [imagej/imagej#89]
See the add-rois tutorial. As written, the tutorial currently shows nothing despite a call to `ij.ui().show(imageDisplay);`. It used to be the case that this showed the object in the default UI, despite that UI not being visible. It is unintuitive that the tutorial now appears to do nothing. We should either: 
- add a `ij.ui().showUI();` call to the tutorial
- make `show(Object);` do something regardless of UI visibility

**Comment by ctrueden** [comment]
Fixed in imagej/tutorials@e3eafd472e1eb56141a9ca771056587c0dfbf239.
